namespace Microsoft.Windows.Storage.Pickers
{
    [contractversion(1)]
    apicontract FileOpenPickerContract {};

    [contract(FileOpenPickerContract, 1)]
    runtimeclass FileOpenPicker
    {
        FileOpenPicker();

        String MyString;

        Windows.Foundation.IAsyncOperation<Windows.Storage.StorageFile> PickSingleFileAsync();
    };
}
