// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace Microsoft.TokuchoNamespace.PurojekutoTenpuretNoFeaturePrefix
{
    [contractversion(1)]
    apicontract PurojekutoTenpuretNoFeaturePrefixContract{};

    [contract(PurojekutoTenpuretNoFeaturePrefixContract, 1)]
    runtimeclass PurojekutoTenpuretNoFeaturePrefixManager
    {
        /// Get a PurojekutoTenpuretNoFeaturePrefix manager for the caller's context.
        static PurojekutoTenpuretNoFeaturePrefixManager Open();

        void TODO_ReplaceMeWithRealContent();
    };
}
