id: 
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner: 
resource: repository
disabled: false
where: 
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - description: Close needs-author-feedback issue with no-recent-activity after 7 days
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isIssue
      - hasLabel:
          label: needs-author-feedback
      - hasLabel:
          label: no-recent-activity
      - noActivitySince:
          days: 7
      actions:
      - closeIssue

    - description: Add no-recent-activity to issue with needs-author-feedback after 7 days
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isIssue
      - hasLabel:
          label: needs-author-feedback
      - noActivitySince:
          days: 7
      - isNotLabeledWith:
          label: no-recent-activity
      actions:
      - addLabel:
          label: no-recent-activity
      - addReply:
          reply: This issue has been automatically marked as stale because it has been marked as requiring author feedback but has not had any activity for **7 days**. It will be closed if no further activity occurs **within 7 days of this comment**.

    - description: Close duplicates after 3 days
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: duplicate
      - noActivitySince:
          days: 3
      actions:
      - addReply:
          reply: This issue has been marked as duplicate and has not had any activity for **3 days**. It will be closed for housekeeping purposes.
      - closeIssue


    eventResponderTasks:

    - description: working on it
      if:
      - payloadType: Pull_Request
      then:
      - inPrLabel:
          label: 'Status: In PR'


    - description: Add needs-triage to new or reopened Issue
      if:
      - payloadType: Issues
      - or:
        - isAction:
            action: Opened
        - isAction:
            action: Reopened
      then:
      - addLabel:
          label: needs-triage


    - description: Remove needs-triage from Closed items
      if:
      - payloadType: Issues
      - isAction:
          action: Closed
      then:
      - removeLabel:
          label: needs-triage


    - description: Add needs-triage to closed item if commented on by external user
      if: 
      - payloadType: Issue_Comment
      - not: isOpen
      - not:
          or:
          - activitySenderHasPermission:
              permission: Write
          - activitySenderHasPermission:
              permission: Admin
      then:
      - addLabel:
          label: needs-triage


    - description: Remove needs-author-feedback after comment from author and add needs-assignee-attention (if issue is assigned)
      if:
      - payloadType: Issue_Comment
      - isAction:
          action: Created
      - isActivitySender:
          issueAuthor: true
      - hasLabel:
          label: needs-author-feedback
      - isAssignedToSomeone
      then:
      - addLabel:
          label: needs-assignee-attention
      - removeLabel:
          label: needs-author-feedback
      

    - description: Remove needs-author-feedback after comment from author and add needs-triage (if issue is unassigned)
      if:
      - payloadType: Issue_Comment
      - isAction:
          action: Created
      - isActivitySender:
          issueAuthor: true
      - hasLabel:
          label: needs-author-feedback
      - not: isAssignedToSomeone
      then:
      - addLabel:
          label: needs-triage
      - removeLabel:
          label: needs-author-feedback
      

    - description: Add needs-triage to new PR
      if:
      - payloadType: Pull_Request
      - or:
        - isAction:
            action: Opened
        - isAction:
            action: Reopened
      then:
      - addLabel:
          label: needs-triage


    - description: Remove needs-author-feedback after comment from author and add needs-triage
      if:
      - payloadType: Issue_Comment
      - isAction:
          action: Created
      - isActivitySender:
          issueAuthor: true
      - hasLabel:
          label: needs-author-feedback
      - isOpen
      then:
      - addLabel:
          label: needs-triage
      - removeLabel:
          label: needs-author-feedback


    - description: Remove no-recent-activity from issue
      if:
      - payloadType: Issues
      - not:
          isAction:
            action: Closed
      - hasLabel:
          label: no-recent-activity
      then:
      - removeLabel:
          label: no-recent-activity
      

    - description: Remove no-recent-activity from issue after comment
      if:
      - payloadType: Issue_Comment
      - hasLabel:
          label: no-recent-activity
      then:
      - removeLabel:
          label: no-recent-activity

    # /feedbackHub
    - description: >-
          Triggers:
          * /feedbackhub
          * /feedbackHub
      if:
      - payloadType: Issue_Comment
      - commentContains:
          pattern: '\/feedback[H|h]ub'
          isRegex: True
      - or:
        - activitySenderHasAssociation:
            association: Owner
        - activitySenderHasAssociation:
            association: Member
      then:
      - addReply:
          reply: >- 
              Hi @${issueAuthor}. Please file this issue on Feedback Hub [Windows]+[f] and paste 
              the link here so we can more easily find your information on the back end. The link 
              can be found at the bottom of the feedback report. Please use "Developer Platform" and "Windows App SDK" 
              for the Category. 
      - removeLabel:
          label: needs-triage
      - removeLabel:
          label: needs-assignee-attention
      - addLabel:
          label: needs-author-feedback
      - closeIssue

    # /feedbackHub_WAIF
    - description: >-
          Triggers:
          * /feedbackhubWAIF
          * /feedbackHubWAIF
      if:
      - payloadType: Issue_Comment
      - commentContains:
          pattern: '\/feedback[H|h]ubWAIF'
          isRegex: True
      - or:
        - activitySenderHasAssociation:
            association: Owner
        - activitySenderHasAssociation:
            association: Member
      then:
      - addReply:
          reply: >- 
              Hi @${issueAuthor}. Could you please submit this issue through Feedback Hub (press [Windows key]+[F])? Once you've done that, share the link here so we can track your issue more effectively on our end.

              When submitting, please select "Developer Platform" as the category and "Windows AI Foundry" as the sub-category.

              Follow these steps:
              1. Open Feedback Hub using [Windows key]+[F]
              2. Make sure you're signed in
              3. When entering your bug details, please start your title with "[Windows AI APIs]"
              4. Choose "Developer Platform" as the category and "Windows AI Foundry" as the sub-category
              5. Under "Add more details", select "Recreate my problem"
              6. Start the recording, show us the issue with your app or sample, then stop recording
              7. Include as many details as you can about how to reproduce the issue
              8. Submit your feedback

              Thanks for helping us improve!

      - removeLabel:
          label: needs-triage
      - removeLabel:
          label: needs-assignee-attention
      - addLabel:
          label: needs-author-feedback

    # /external
    - description: >-
          Triggers:
          * /external
          * /External
      if:
      - payloadType: Issue_Comment
      - commentContains:
          pattern: '\/[E|e]xternal'
          isRegex: True
      - or:
        - activitySenderHasAssociation:
            association: Owner
        - activitySenderHasAssociation:
            association: Member
      then:
      - addReply:
          reply: >- 
              [external-classification] Hi @${issueAuthor}, thank you for your contribution! This issue appears to be external to the WindowsAppSDK.
              To help route it appropriately, please submit your feedback via the Feedback Hub by pressing [Windows] + [F],
              and include detailed information and diagnostics. We appreciate your help in improving the platform!
      - removeLabel:
          label: needs-triage
      - removeLabel:
          label: needs-assignee-attention
      - addLabel:
          label: area-External

    - description: Close /external issues (step 2)
      if:
      - hasLabel:
          label: area-External
      - isOpen
      - commentContains:
          pattern: '^\[external-classification\]'
          isRegex: True
      - or:
        - activitySenderHasPermission:
            permission: Write
        - activitySenderHasPermission:
            permission: Admin
      then:
      - closeIssue

onFailure: 
onSuccess: 
