namespace Microsoft.SampleWinRT
{
    runtimeclass Common
    {
        static void Initialize();

        static String AppIdentity { get; };

        static Boolean IsAppContainer{ get; };
        static Boolean HasIdentity{ get; };
    };
}
