// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace Microsoft.Kozani.MakeMSIX
{
    [contractversion(1)]
    apicontract MakeMSIXContract{};

    [contract(MakeMSIXContract, 1)]
    runtimeclass MakeMSIXManager
    {
        /// Get a MakeMSIX manager for the caller's context.
        static MakeMSIXManager Open();

        void TODO_ReplaceMeWithRealContent();
    };
}
