// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

#include <TerminalVelocityFeatures-VersionInfo.h>

namespace Microsoft.Windows.ApplicationModel.WindowsAppRuntime
{
    [feature(Feature_VersionInfoAPI)]
    [contractversion(1)]
    apicontract VersionInfoContract{};

    /// Version information for the Windows App SDK release.
    [feature(Feature_VersionInfoAPI)]
    [contract(VersionInfoContract, 1)]
    static runtimeclass ReleaseInfo
    {
        /// The major version of the Windows App SDK release.
        static UInt16 Major{ get; };

        /// The minor version of the Windows App SDK release.
        static UInt16 Minor{ get; };

        /// The patch version of the Windows App SDK release.
        static UInt16 Patch{ get; };

        /// The Windows App SDK release's version tag; for example, "preview2", or empty string for stable.
        static String VersionTag{ get; };

        /// The version of the Windows App SDK runtime; for example, "1.1-preview2" or "1.2.3".
        static String AsString{ get; };
    };

    /// Version information for the Windows App SDK runtime.
    [feature(Feature_VersionInfoAPI)]
    [contract(VersionInfoContract, 1)]
    static runtimeclass RuntimeInfo
    {
        /// The version of the Windows App SDK runtime; for example, { Major=1000, Minor=446, Build=804, Revision=0 }
        static Windows.ApplicationModel.PackageVersion Version{ get; };

        /// The version of the Windows App SDK runtime; for example, "1000.446.804.0"
        static String AsString{ get; };
    };
}
