version: 2
updates:
  - package-ecosystem: "nuget"
    directories:
      - "/"
      - "/dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/UnpackagedTests"
      - "/dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/projection"
      - "/dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/unittests"
      - "/dev/Templates/VSIX"
      - "/test/StaticValidationTests"
      - "/tools/ProjectTemplates/dev.cs.dll.projection"
    schedule:
      interval: "monthly"
    groups:
      minor-and-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      minor-and-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
