// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AppAttachExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "AppAttachExtension.3836b090-4cfc-427d-8008-ed1f9ebc4d97";
        public const string Name = "AppAttachExtension";
        public const string Description = @"This visual studio extension enable developers to generate App Attach ready packages. Currently this supports WinUI3 applications.";
        public const string Language = "en-US";
        public const string Version = "0.1";
        public const string Author = "Microsoft";
        public const string Tags = "";
    }
}
