// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

#ifndef __PROJECTREUNION_TEST_METADATA_H
#define __PROJECTREUNION_TEST_METADATA_H

#define PROJECTREUNION_TEST_METADATA_VERSION            0x0004000107AF014DLLu
#define PROJECTREUNION_TEST_METADATA_VERSION_MAJOR      4
#define PROJECTREUNION_TEST_METADATA_VERSION_MINOR      1
#define PROJECTREUNION_TEST_METADATA_VERSION_BUILD      1967
#define PROJECTREUNION_TEST_METADATA_VERSION_REVISION   333
#define PROJECTREUNION_TEST_METADATA_VERSION_STRING     L"4.1.1967.333"

#define PROJECTREUNION_TEST_MSIX_PUBLISHERID            L"8wekyb3d8bbwe"

#define PROJECTREUNION_TEST_MSIX_FRAMEWORK_PACKAGE_NAME L"Microsoft.ProjectReunion.Framework"
#define PROJECTREUNION_TEST_MSIX_DDLM_PACKAGE_NAME      L"Microsoft.ProjectReunion.DDLM"
#define PROJECTREUNION_TEST_MSIX_MAIN_PACKAGE_NAME      L"Microsoft.ProjectReunion.Main"

#define PROJECTREUNION_TEST_PACKAGE_DDLM_NAMEPREFIX     L"ProjectReunion.Test.DDLM"
#define PROJECTREUNION_TEST_PACKAGE_DDLM_VERSION        PROJECTREUNION_TEST_MSIX_MAIN_PACKAGE_NAME


#define MSIX_PACKAGE_ARCHITECTURE_ARM       L"arm"
#define MSIX_PACKAGE_ARCHITECTURE_ARM64     L"arm64"
#define MSIX_PACKAGE_ARCHITECTURE_NEUTRAL   L"neutral"
#define MSIX_PACKAGE_ARCHITECTURE_X64       L"x64"
#define MSIX_PACKAGE_ARCHITECTURE_X86       L"x86"

#if defined(_M_X64)
#define PROJECTREUNION_TEST_PACKAGE_DDLM_ARCHITECTURE   MSIX_PACKAGE_ARCHITECTURE_X64
#elif defined(_M_IX86)
#define PROJECTREUNION_TEST_PACKAGE_DDLM_ARCHITECTURE   MSIX_PACKAGE_ARCHITECTURE_X86
#elif defined(_M_ARM64)
#define PROJECTREUNION_TEST_PACKAGE_DDLM_ARCHITECTURE   MSIX_PACKAGE_ARCHITECTURE_ARM64
#elif defined(_M_ARM)
#define PROJECTREUNION_TEST_PACKAGE_DDLM_ARCHITECTURE   MSIX_PACKAGE_ARCHITECTURE_ARM
#else
#   error "Unknown processor architecture"
#endif
#define PROJECTREUNION_TEST_PACKAGE_DDLM_NAME           PROJECTREUNION_TEST_PACKAGE_DDLM_NAMEPREFIX L"-" PROJECTREUNION_TEST_METADATA_VERSION_STRING  L"-" PROJECTREUNION_TEST_PACKAGE_DDLM_ARCHITECTURE
#define PROJECTREUNION_TEST_PACKAGE_DDLM_PUBLISHERID    PROJECTREUNION_TEST_MSIX_PUBLISHERID
#define PROJECTREUNION_TEST_PACKAGE_DDLM_FAMILYNAME     PROJECTREUNION_TEST_PACKAGE_DDLM_NAME L"_" PROJECTREUNION_TEST_PACKAGE_DDLM_PUBLISHERID
#define PROJECTREUNION_TEST_PACKAGE_DDLM_FULLNAME       PROJECTREUNION_TEST_PACKAGE_DDLM_NAME L"_" PROJECTREUNION_TEST_PACKAGE_DDLM_VERSION L"_" PROJECTREUNION_TEST_PACKAGE_DDLM_ARCHITECTURE L"__" PROJECTREUNION_TEST_PACKAGE_DDLM_PUBLISHERID

#endif //__PROJECTREUNION_TEST_METADATA_H
