// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

#ifndef __WINDOWSAPPSDK_TEST_METADATA_H
#define __WINDOWSAPPSDK_TEST_METADATA_H

#define WINDOWSAPPSDK_TEST_METADATA_VERSION            0x0004000107AF014DLLu
#define WINDOWSAPPSDK_TEST_METADATA_VERSION_MAJOR      4
#define WINDOWSAPPSDK_TEST_METADATA_VERSION_MINOR      1
#define WINDOWSAPPSDK_TEST_METADATA_VERSION_BUILD      1967
#define WINDOWSAPPSDK_TEST_METADATA_VERSION_REVISION   333
#define WINDOWSAPPSDK_TEST_METADATA_VERSION_STRING     L"4.1.1967.333"

#define WINDOWSAPPSDK_TEST_MSIX_PUBLISHERID            L"8wekyb3d8bbwe"

#define WINDOWSAPPSDK_TEST_MSIX_FRAMEWORK_PACKAGE_NAME L"Microsoft.WindowsAppSDK.Framework"
#define WINDOWSAPPSDK_TEST_MSIX_DDLM_PACKAGE_NAME      L"Microsoft.WindowsAppSDK.DDLM"
#define WINDOWSAPPSDK_TEST_MSIX_MAIN_PACKAGE_NAME      L"Microsoft.WindowsAppSDK.Main"
#define WINDOWSAPPSDK_TEST_MSIX_SINGLETON_PACKAGE_NAME L"Microsoft.WindowsAppSDK.Singleton"

#define WINDOWSAPPSDK_TEST_PACKAGE_DDLM_NAMEPREFIX     L"WindowsAppSDK.Test.DDLM"
#define WINDOWSAPPSDK_TEST_PACKAGE_DDLM_VERSION        WINDOWSAPPSDK_TEST_MSIX_MAIN_PACKAGE_NAME


#define MSIX_PACKAGE_ARCHITECTURE_ARM       L"arm"
#define MSIX_PACKAGE_ARCHITECTURE_ARM64     L"arm64"
#define MSIX_PACKAGE_ARCHITECTURE_NEUTRAL   L"neutral"
#define MSIX_PACKAGE_ARCHITECTURE_X64       L"x64"
#define MSIX_PACKAGE_ARCHITECTURE_X86       L"x86"

#if defined(_M_X64)
#define WINDOWSAPPSDK_TEST_PACKAGE_DDLM_ARCHITECTURE   MSIX_PACKAGE_ARCHITECTURE_X64
#elif defined(_M_IX86)
#define WINDOWSAPPSDK_TEST_PACKAGE_DDLM_ARCHITECTURE   MSIX_PACKAGE_ARCHITECTURE_X86
#elif defined(_M_ARM64)
#define WINDOWSAPPSDK_TEST_PACKAGE_DDLM_ARCHITECTURE   MSIX_PACKAGE_ARCHITECTURE_ARM64
#elif defined(_M_ARM)
#define WINDOWSAPPSDK_TEST_PACKAGE_DDLM_ARCHITECTURE   MSIX_PACKAGE_ARCHITECTURE_ARM
#else
#   error "Unknown processor architecture"
#endif
#define WINDOWSAPPSDK_TEST_PACKAGE_DDLM_NAME           WINDOWSAPPSDK_TEST_PACKAGE_DDLM_NAMEPREFIX L"-" WINDOWSAPPSDK_TEST_METADATA_VERSION_STRING  L"-" WINDOWSAPPSDK_TEST_PACKAGE_DDLM_ARCHITECTURE
#define WINDOWSAPPSDK_TEST_PACKAGE_DDLM_PUBLISHERID    WINDOWSAPPSDK_TEST_MSIX_PUBLISHERID
#define WINDOWSAPPSDK_TEST_PACKAGE_DDLM_FAMILYNAME     WINDOWSAPPSDK_TEST_PACKAGE_DDLM_NAME L"_" WINDOWSAPPSDK_TEST_PACKAGE_DDLM_PUBLISHERID
#define WINDOWSAPPSDK_TEST_PACKAGE_DDLM_FULLNAME       WINDOWSAPPSDK_TEST_PACKAGE_DDLM_NAME L"_" WINDOWSAPPSDK_TEST_PACKAGE_DDLM_VERSION L"_" WINDOWSAPPSDK_TEST_PACKAGE_DDLM_ARCHITECTURE L"__" WINDOWSAPPSDK_TEST_PACKAGE_DDLM_PUBLISHERID

#endif //__WINDOWSAPPSDK_TEST_METADATA_H
