// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

import "oaidl.idl";
import "ocidl.idl";

#include "..\DynamicDependencyDataStore-Constants.h"

[object]
[uuid(DDEB4D6A-E146-476d-B729-0BFB1A29A86E)]
[pointer_default(unique)]
interface IDynamicDependencyDataStore : IUnknown
{
    HRESULT GetApplicationData([out, retval] IUnknown** applicationData);

    HRESULT GetPackageFullName([out, retval] LPWSTR* packageFullName);
};

[uuid(PR_DYNDEP_LIBID_UUID)]
[version(1.0)]
library DynamicDependencyDataStoreLib
{
    [uuid(PR_DYNDEP_DATASTORE_CLSID_UUID)]
    coclass DynamicDependencyDataStore
    {
        [default] interface IDynamicDependencyDataStore;
    };
};
