// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

namespace $rootnamespace$
{
    [default_interface]
    runtimeclass $safeitemname$ : Microsoft.UI.Xaml.Controls.UserControl
    {
        $safeitemname$();
        Int32 MyProperty;
    }
}
