// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

import "oaidl.idl";
import "ocidl.idl";

#include "..\PurojekutoTenpuret\PurojekutoTenpuret-Constants.h"

#include "PurojekutoTenpuretInterface.idl"

[uuid(PR_PUROJEKUTOTENPURET_LIBID_UUID)]
[version(1.0)]
library PurojekutoTenpuret
{
    [uuid(PR_PUROJEKUTOTENPURET_CLSID_UUID)]
    coclass PurojekutoTenpuret
    {
        [default] interface IPurojekutoTenpuret;
    };
};
