// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

namespace Microsoft.ProjectReunion
{
    runtimeclass EnvironmentWriter
    {
        static EnvironmentWriter GetForProcess();
        static EnvironmentWriter GetForUser();
        static EnvironmentWriter GetForMachine();

        Boolean IsSupported{ get; };

        void SetEnvironmentVariable(String name, String value);

        // Path manipulation
        void AppendToPath(String path);
        void RemoveFromPath(String path);

        // PathExt Manipulation
        void AddExecutableFileExtension(String pathExt);
        void RemoveExecutableFileExtension(String pathExt);
    }
}
