namespace Microsoft.ProjectReunion
{
    runtimeclass EnvironmentManager
    {
        static EnvironmentManager GetForProcess();
        static EnvironmentManager GetForUser();
        static EnvironmentManager GetForMachine();

        IMapView<String, String> GetEnvironmentVariables();

        String GetEnvironmentVariable(String name);
        void SetEnvironmentVariable(String name, String value);

        // Path manipulation
        void AppendToPath(String path);
        void RemoveFromPath(String path);

        // PathExt Manipulation
        void AddExecutableFileExtension(String pathExt);
        void RemoveExecutableFileExtension(String pathExt);
    }
}
