// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

import "oaidl.idl";
import "ocidl.idl";

[object]
[uuid(b15f509e-2779-4ccb-b36a-aea8331ff6d7)]
[pointer_default(unique)]
interface IKozaniRemoteManager : IUnknown
{
    HRESULT Initialize();

    HRESULT Shutdown();
};
