// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

import "oaidl.idl";
import "ocidl.idl";

[object]
[uuid(fe870cd2-3919-415a-b89e-4d3e1e1d7a14)]
[pointer_default(unique)]
interface IKozaniRemoteManager : IUnknown
{
    HRESULT Initialize();

    HRESULT Shutdown();
};
