name: Bug report
description: File a bug report
title: "Bug title"
labels: []
body:
  - type: markdown
    attributes:
      value: |
        For bugs related to WinUI, please open a bug on the [Microsoft.UI.Xaml repository](https://github.com/microsoft/microsoft-ui-xaml)
        Please provide the title, description, and reproduction steps in English. Thank you!
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the bug
      description: Please enter a short, clear description of the bug.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Steps to reproduce the bug
      description: Please provide any required setup and steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
  - type: textarea
    attributes:
      label: Expected behavior
      description: Please provide a description of what you expected to happen
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots here to help explain your problem
  - type: dropdown
    attributes:
      label: NuGet package version
      description: Specify the version of Windows App SDK (or Project Reunion) you're using.
      options:
        - "Windows App SDK 1.8.3: 1.8.251106002"
        - "Windows App SDK 1.8 Preview 1: 1.8.250814004-preview1"
        - "Windows App SDK 2.0 Experimental 3: 2.0.0-experimental3"
  - type: dropdown
    attributes:
      label: Packaging type
      description: Please specify the packaging type you're using when you encountered the issue.
      multiple: true
      options:
        - "Packaged (MSIX)"
        - "Unpackaged"
  - type: dropdown
    attributes:
      label: Windows version
      description: Which Windows versions did you see the issue on?
      multiple: true
      options:
        - "Insider Build (xxxxx)"
        - "Windows 11 version 24H2 LTSC (26100, June Update)"
        - "Windows 11 version 24H2 (26100, June 2025 Update)"
        - "Windows 11 version 23H2 (22631, June 2025 Update)"
        - "Windows 11 version 22H2 (22621, 2022 Update)"
        - "Windows 11 version 21H2 (22000)"
        - "Windows 10 version 22H2 (19045, 2022 Update)"
        - "Windows 10 version 21H2 (19044, November 2021 Update)"
        - "Windows 10 version 21H1 (19043, May 2021 Update)"
        - "Windows 10 version 20H2 (19042, October 2020 Update)"
        - "Windows 10 version 2004 (19041, May 2020 Update)"
        - "Windows 10 version 1909 (18363, November 2019 Update)"
        - "Windows 10 version 1903 (18362, May 2019 Update)"
        - "Windows 10 version 1809 (17763, October 2018 Update)"
  - type: dropdown
    attributes:
      label: IDE
      description: Which IDE are you using?
      multiple: true
      options:
        - "Visual Studio 2022-preview"
        - "Visual Studio 2022"
        - "Visual Studio 2019"
        - "Other"
  - type: textarea
    attributes:
      label: Additional context
      description: Enter any other applicable info here
