//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsAppSDK.TemplateUtilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    var assembly = typeof(Resources).Assembly;
                    var assemblyName = assembly.GetName().Name;
                    
                    // Determine the resource base name based on the executing assembly
                    string resourceBaseName;
                    var fallbackAssemblyName = "WindowsAppSDK.Cs.Extension";
                    var match = System.Text.RegularExpressions.Regex.Match(assemblyName, @"^(WindowsAppSDK\.(Cpp|Cs)\.Extension)");
                    var baseAssemblyName = match.Success ? match.Groups[1].Value : fallbackAssemblyName;
                    resourceBaseName = baseAssemblyName + ".Resources.Resources";

                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(resourceBaseName, assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComponentModel service is not available..
        /// </summary>
        public static string ErrorComponentModelNotAvailable {
            get {
                return ResourceManager.GetString("ErrorComponentModelNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install NuGet package: {0}. Error: {1}.
        /// </summary>
        public static string ErrorFailedToInstallPackage {
            get {
                return ResourceManager.GetString("ErrorFailedToInstallPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not obtain IVsPackageInstaller service..
        /// </summary>
        public static string ErrorPackageInstallerNotAvailable {
            get {
                return ResourceManager.GetString("ErrorPackageInstallerNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following NuGet packages failed to install: {0}.
        /// </summary>
        public static string ErrorPackagesFailedToInstall {
            get {
                return ResourceManager.GetString("ErrorPackagesFailedToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project reference is null. Likely a ProjectGroup vstemplate..
        /// </summary>
        public static string ErrorProjectReferenceNull {
            get {
                return ResourceManager.GetString("ErrorProjectReferenceNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveAllProjects must be called on the UI thread..
        /// </summary>
        public static string ErrorSaveAllProjectsUIThread {
            get {
                return ResourceManager.GetString("ErrorSaveAllProjectsUIThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage NuGet Packages.
        /// </summary>
        public static string InfoBarManageNuGetPackages {
            get {
                return ResourceManager.GetString("InfoBarManageNuGetPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation in progress....
        /// </summary>
        public static string NuGetInstallDialogStatus {
            get {
                return ResourceManager.GetString("NuGetInstallDialogStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing NuGet packages into project....
        /// </summary>
        public static string NuGetInstallDialogTitle {
            get {
                return ResourceManager.GetString("NuGetInstallDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Could not obtain IComponentModel service..
        /// </summary>
        public static string WarningComponentModelNotAvailable {
            get {
                return ResourceManager.GetString("WarningComponentModelNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Could not obtain IVsThreadedWaitDialog2 service..
        /// </summary>
        public static string WarningThreadedWaitDialogNotAvailable {
            get {
                return ResourceManager.GetString("WarningThreadedWaitDialogNotAvailable", resourceCulture);
            }
        }
    }
}
