// <auto-generated/>
namespace WindowsAppSDK.TemplateUtilities {
    using System;
    using System.Reflection;
    using System.Resources;
    using System.Globalization;
    public static class Resources {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;
        
        public static string NuGetInstallDialogTitle {
            get {
                return ResourceManager.GetString("NuGetInstallDialogTitle", resourceCulture);
            }
        }
        
        public static string NuGetInstallDialogStatus {
            get {
                return ResourceManager.GetString("NuGetInstallDialogStatus", resourceCulture);
            }
        }
        
        public static string WarningComponentModelNotAvailable {
            get {
                return ResourceManager.GetString("WarningComponentModelNotAvailable", resourceCulture);
            }
        }
        
        public static string WarningThreadedWaitDialogNotAvailable {
            get {
                return ResourceManager.GetString("WarningThreadedWaitDialogNotAvailable", resourceCulture);
            }
        }
        
        public static string ErrorComponentModelNotAvailable {
            get {
                return ResourceManager.GetString("ErrorComponentModelNotAvailable", resourceCulture);
            }
        }
        
        public static string ErrorPackageInstallerNotAvailable {
            get {
                return ResourceManager.GetString("ErrorPackageInstallerNotAvailable", resourceCulture);
            }
        }
        
        public static string ErrorProjectReferenceNull {
            get {
                return ResourceManager.GetString("ErrorProjectReferenceNull", resourceCulture);
            }
        }
        
        public static string ErrorFailedToInstallPackage {
            get {
                return ResourceManager.GetString("ErrorFailedToInstallPackage", resourceCulture);
            }
        }
        
        public static string ErrorPackagesFailedToInstall {
            get {
                return ResourceManager.GetString("ErrorPackagesFailedToInstall", resourceCulture);
            }
        }
        
        public static string ErrorSaveAllProjectsUIThread {
            get {
                return ResourceManager.GetString("ErrorSaveAllProjectsUIThread", resourceCulture);
            }
        }
        
        public static string InfoBarManageNuGetPackages {
            get {
                return ResourceManager.GetString("InfoBarManageNuGetPackages", resourceCulture);
            }
        }
        
        private static ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    resourceMan = new ResourceManager("WindowsAppSDK.TemplateUtilities.Resources", typeof(Resources).Assembly);
                }
                return resourceMan;
            }
        }
        
        public static CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }
    }
}
