// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace StoragePickersTestApp
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
    }
}
