// Copyright (c) Microsoft Corp. Licensed under the MIT license.

import "inspectable.idl";
import "AsyncInfo.idl";
import "EventToken.idl";
import "Windows.Foundation.idl";
import "Windows.Foundation.Metadata.idl";
import "Windows.Security.EnterpriseData.idl";
import "Windows.Storage.idl";
import "Windows.Storage.Streams.idl";
import "Windows.UI.idl";
#include <sdkddkver.h>

// Forward declarations
namespace Windows.Foundation
{
  typedef struct DateTime DateTime;
  runtimeclass Uri;
}

namespace Windows.Foundation.Metadata
{

  // FIXME: Figure out how to actually forward declare/prototype this WinRT Foundation attribute
  // without defining it

  [attributeusage(target_all)]
  [attributename("hasvariant")]
  [version(NTDDI_WIN8)]
  attribute HasVariantAttribute
  {
  }
}

namespace Windows.Security.EnterpriseData
{
  typedef enum ProtectionPolicyEvaluationResult ProtectionPolicyEvaluationResult;
}

namespace Windows.Storage
{
  interface IStorageItem;
  interface IStorageFile;
  runtimeclass StorageFile;
}

namespace Windows.Storage.Streams
{
  interface IRandomAccessStreamReference;
  runtimeclass RandomAccessStreamReference;
}

namespace Windows.UI
{
  typedef struct Color Color;
}

namespace Microsoft.ProjectReunion.ApplicationModel
{
  [contractversion(1.0)]
  apicontract ClipboardContract { };

  delegate DataProviderHandler;
  runtimeclass Clipboard;
  runtimeclass ClipboardContentOptions;
  runtimeclass ClipboardHistoryItem;
  runtimeclass ClipboardHistoryItemsResult;
  runtimeclass DataPackage;
  runtimeclass DataPackagePropertySet;
  runtimeclass DataPackagePropertySetView;
  runtimeclass DataPackageView;
  runtimeclass DataProviderDeferral;
  runtimeclass DataProviderRequest;
  runtimeclass HtmlFormatHelper;
  runtimeclass OperationCompletedEventArgs;
  runtimeclass StandardDataFormats;
}

// Generic instantiations
namespace Microsoft.ProjectReunion.ApplicationModel
{
  declare
  {
    interface Windows.Foundation.Collections.IIterable<ClipboardHistoryItem*>;
    interface Windows.Foundation.Collections.IIterator<ClipboardHistoryItem*>;
    interface Windows.Foundation.Collections.IVectorView<ClipboardHistoryItem*>;
    interface Windows.Foundation.IAsyncOperation<ClipboardHistoryItemsResult*>;
    interface Windows.Foundation.IAsyncOperation<DataPackage*>;
    interface Windows.Foundation.IAsyncOperation<DataPackageOperation>;
    interface Windows.Foundation.TypedEventHandler<DataPackage*, IInspectable*>;
    interface Windows.Foundation.TypedEventHandler<DataPackage*, OperationCompletedEventArgs*>;
  }
}

// Type definitions
namespace Microsoft.ProjectReunion.ApplicationModel
{

  // FIXME: Figure out how to declare these enums without causing definition conflicts
  // between the enum constants and the same-named ones in
  // Windows.ApplicationModel.DataTransfer

  [contract(ClipboardContract, 1.0)]
  enum ClipboardHistoryItemsResultStatus
  {
    aaaSuccess                  = 0,
    aaaAccessDenied             = 1,
    aaaClipboardHistoryDisabled = 2,
  };

  [contract(ClipboardContract, 1.0)]
  [flags]
  enum DataPackageOperation
  {
    // TODO: combine Copy and Move?
    aaaNone = 0x0,
    aaaCopy = 0x1,
    aaaMove = 0x2,
    aaaLink = 0x4,
  };

  [contract(ClipboardContract, 1.0)]
  enum SetHistoryItemAsContentStatus
  {
    aaaSuccess      = 0,
    aaaAccessDenied = 1,
    aaaItemDeleted  = 2,
  };

  /// <summary>
  /// Prototype for functions that will be called to render a delay-rendered
  /// data format in a <see cref="DataPackage"/>.
  /// </summary>
  [contract(ClipboardContract, 1.0)]
  delegate void DataProviderHandler(DataProviderRequest request);

  /// <summary>
  /// Top-level API for reading, writing, and monitoring the system clipboard,
  /// as well as clipboard history, if available on the current Windows version
  /// and enabled by the user. Clipboard history also includes clipboard items
  /// roamed from your other devices through the cloud.
  /// </summary>
  [contract(ClipboardContract, 1.0)]
  [marshaling_behavior(standard)]
  static runtimeclass Clipboard
  {
    static DataPackageView GetContent();
    static void SetContent(DataPackage content);

    static void Flush();
    static void Clear();

    static event Windows.Foundation.EventHandler<Object> ContentChanged;

    static Windows.Foundation.IAsyncOperation<ClipboardHistoryItemsResult> GetHistoryItemsAsync();
    static Boolean ClearHistory();
    static Boolean DeleteItemFromHistory(ClipboardHistoryItem item);
    static SetHistoryItemAsContentStatus SetHistoryItemAsContent(ClipboardHistoryItem item);
    static Boolean IsHistoryEnabled();
    static Boolean IsRoamingEnabled();

    static Boolean SetContentWithOptions(DataPackage content, ClipboardContentOptions options);

    static event Windows.Foundation.EventHandler<Object> HistoryChanged;
    static event Windows.Foundation.EventHandler<Object> RoamingEnabledChanged;
    static event Windows.Foundation.EventHandler<Object> HistoryEnabledChanged;
  }

  /// <summary>
  /// Clipboard history-related settings your app can set for a new item
  /// that it cuts or copies onto the clipboard using
  /// <see cref="Clipboard.SetContentWithOptions"/>.
  /// </summary>
  [contract(ClipboardContract, 1.0)]
  runtimeclass ClipboardContentOptions
  {
    ClipboardContentOptions();

    Boolean IsRoamable;
    Boolean IsAllowedInHistory;
    Windows.Foundation.Collections.IVector<String> RoamingFormats { get; };
    Windows.Foundation.Collections.IVector<String> HistoryFormats { get; };
  }

  /// <summary>
  /// An item retrieved from the clipboard history log.
  /// </summary>
  [contract(ClipboardContract, 1.0)]
  runtimeclass ClipboardHistoryItem
  {
    String Id { get; };
    Windows.Foundation.DateTime Timestamp { get; };
    DataPackageView Content { get; };
  }

  /// <summary>
  /// Return value for a call to <see cref="Clipboard.GetHistoryItemsAsync"/>.
  /// </summary>
  [contract(ClipboardContract, 1.0)]
  runtimeclass ClipboardHistoryItemsResult
  {
    ClipboardHistoryItemsResultStatus Status { get; };
    Windows.Foundation.Collections.IVectorView<ClipboardHistoryItem> Items { get; };
  }

  /// <summary>
  /// Basic unit of data transfer for <see cref="Clipboard"/>.
  /// Allows data to be sent in multiple "formats". Certain formats can be
  /// "delay rendered", meaning they are not serialized immediately into
  /// the DataPackage, but instead a creator-provided callback will
  /// serialize them on demand.
  /// </summary>
  [contract(ClipboardContract, 1.0)]
  runtimeclass DataPackage
  {
    DataPackage();

    DataPackageView GetView();
    DataPackagePropertySet Properties { get; };
    DataPackageOperation RequestedOperation;
    event Windows.Foundation.TypedEventHandler<DataPackage, OperationCompletedEventArgs> OperationCompleted;
    event Windows.Foundation.TypedEventHandler<DataPackage, Object> Destroyed;
    void SetData(String formatId, [hasvariant] Object value);
    void SetDataProvider(String formatId, DataProviderHandler delayRenderer);
    void SetText(String value);
    void SetHtmlFormat(String value);

    // typically used with SetHtmlFormat to include images, other secondary resources with the HTML
    Windows.Foundation.Collections.IMap<String, Windows.Storage.Streams.RandomAccessStreamReference> ResourceMap { get; };

    void SetRtf(String value);
    void SetBitmap(Windows.Storage.Streams.RandomAccessStreamReference value);

    [method_name("SetStorageItemsReadOnly")]
    void SetStorageItems(Windows.Foundation.Collections.IIterable<Windows.Storage.IStorageItem> value);
    [method_name("SetStorageItems")]
    void SetStorageItems(Windows.Foundation.Collections.IIterable<Windows.Storage.IStorageItem> value, Boolean readOnly);

    void SetApplicationLink(Windows.Foundation.Uri value);
    void SetWebLink(Windows.Foundation.Uri value);
  }

  /// <summary>
  /// Read-only view of a <see cref="DataPackage"/>.
  /// </summary>
  [contract(ClipboardContract, 1.0)]
  runtimeclass DataPackageView
  {
    DataPackagePropertySetView Properties { get; };

    DataPackageOperation RequestedOperation { get; };
    void ReportOperationCompleted(DataPackageOperation operation);

    Windows.Foundation.Collections.IVectorView<String> AvailableFormats { get; };
    Boolean Contains(String formatId);

    Windows.Foundation.IAsyncOperation<Object> GetDataAsync(String formatId);

    [method_name("GetTextAsync")]
    Windows.Foundation.IAsyncOperation<String> GetTextAsync();
    [method_name("GetCustomTextAsync")]
    Windows.Foundation.IAsyncOperation<String> GetTextAsync(String formatId);

    Windows.Foundation.IAsyncOperation<String> GetHtmlFormatAsync();
    Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IMapView<String, Windows.Storage.Streams.RandomAccessStreamReference> > GetResourceMapAsync();
    Windows.Foundation.IAsyncOperation<String> GetRtfAsync();
    Windows.Foundation.IAsyncOperation<Windows.Storage.Streams.RandomAccessStreamReference> GetBitmapAsync();
    Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVectorView<Windows.Storage.IStorageItem> > GetStorageItemsAsync();

    Windows.Foundation.IAsyncOperation<Windows.Foundation.Uri> GetApplicationLinkAsync();
    Windows.Foundation.IAsyncOperation<Windows.Foundation.Uri> GetWebLinkAsync();

    [method_name("RequestAccessAsync")]
    Windows.Foundation.IAsyncOperation<Windows.Security.EnterpriseData.ProtectionPolicyEvaluationResult> RequestAccessAsync();
    [method_name("RequestAccessWithEnterpriseIdAsync")]
    Windows.Foundation.IAsyncOperation<Windows.Security.EnterpriseData.ProtectionPolicyEvaluationResult> RequestAccessAsync(String enterpriseId);
    Windows.Security.EnterpriseData.ProtectionPolicyEvaluationResult UnlockAndAssumeEnterpriseIdentity();

    // FIXME: poorly documented on docs.microsoft.com - what does it do? why is in a View class?
    void SetAcceptedFormatId(String formatId);
  }

  /// <summary>
  /// A set of metadata properties for a <see cref="DataPackage"/>.
  /// Contains strongly-typed WinRT properties for common descriptors
  /// of the data or source app, but also allows setting arbitrary key-value mappings.
  /// </summary>
  [contract(ClipboardContract, 1.0)]
  runtimeclass DataPackagePropertySet :
    [default] IDataPackagePropertySet
    , Windows.Foundation.Collections.IMap<String, Object>
    , Windows.Foundation.Collections.IIterable<Windows.Foundation.Collections.IKeyValuePair<String, Object> >
  { }

  [contract(ClipboardContract, 1.0)]
  [exclusiveto(DataPackagePropertySet)]
  [hasvariant]
  interface IDataPackagePropertySet requires
    Windows.Foundation.Collections.IMap<String, Object>
    , Windows.Foundation.Collections.IIterable<Windows.Foundation.Collections.IKeyValuePair<String, Object> >
  {
    String Title;
    String Description;
    Windows.Storage.Streams.IRandomAccessStreamReference Thumbnail;
    Windows.Foundation.Collections.IVector<String> FileTypes { get; };
    String ApplicationName;
    Windows.Foundation.Uri ApplicationListingUri;

    Windows.Foundation.Uri ContentSourceWebLink;
    Windows.Foundation.Uri ContentSourceApplicationLink;
    String PackageFamilyName;
    Windows.Storage.Streams.IRandomAccessStreamReference Square30x30Logo;
    Windows.UI.Color LogoBackgroundColor;

    String EnterpriseId;

    String ContentSourceUserActivityJson;
  }

  /// <summary>
  /// Read-only view of a <see cref="DataPackagePropertySet"/>.
  /// </summary>
  [contract(ClipboardContract, 1.0)]
  runtimeclass DataPackagePropertySetView :
    [default] IDataPackagePropertySetView
    , Windows.Foundation.Collections.IMapView<String, Object>
    , Windows.Foundation.Collections.IIterable<Windows.Foundation.Collections.IKeyValuePair<String, Object> >
  { }

  [contract(ClipboardContract, 1.0)]
  [exclusiveto(DataPackagePropertySetView)]
  [hasvariant]
  interface IDataPackagePropertySetView requires
    Windows.Foundation.Collections.IMapView<String, Object>
    , Windows.Foundation.Collections.IIterable<Windows.Foundation.Collections.IKeyValuePair<String, Object> >
  {
    String Title { get; };
    String Description { get; };
    Windows.Storage.Streams.IRandomAccessStreamReference Thumbnail { get; };
    Windows.Foundation.Collections.IVectorView<String> FileTypes { get; };
    String ApplicationName { get; };
    Windows.Foundation.Uri ApplicationListingUri { get; };

    String PackageFamilyName { get; };
    Windows.Foundation.Uri ContentSourceWebLink { get; };
    Windows.Foundation.Uri ContentSourceApplicationLink { get; };
    Windows.Storage.Streams.IRandomAccessStreamReference Square30x30Logo { get; };
    Windows.UI.Color LogoBackgroundColor { get; };

    String EnterpriseId { get; };

    String ContentSourceUserActivityJson { get; };

    Boolean IsFromRoamingClipboard { get; };
  }

  /// <summary>
  /// An acknowledgement by the system that your app is in the process of
  /// a delay rendering, with the ability to signal the system when done.
  /// </summary>
  [contract(ClipboardContract, 1.0)]
  runtimeclass DataProviderDeferral
  {
    void Complete();
  }

  /// <summary>
  /// Input to a <see cref="DataProviderHandler"/> function for delay-rendering.
  /// </summary>
  [contract(ClipboardContract, 1.0)]
  runtimeclass DataProviderRequest
  {
    String FormatId { get; };
    Windows.Foundation.DateTime Deadline { get; };
    DataProviderDeferral GetDeferral();
    void SetData(Object value);
  }

  /// <summary>
  /// Translates strings containing fragments of HTML to and from the special format
  /// used by <see cref="StandardDataFormats.Html"/>, described here:
  /// https://docs.microsoft.com/windows/win32/dataxchg/html-clipboard-format
  /// </summary>
  static runtimeclass HtmlFormatHelper
  {
    static String GetStaticFragment(String htmlFormat);
    static String CreateHtmlFormat(String htmlFragment);
  }

  /// <summary>
  /// Input parameters for <see cref="DataPackage.OperationCompleted"/> event handler functions.
  /// </summary>
  [contract(ClipboardContract, 1.0)]
  runtimeclass OperationCompletedEventArgs
  // FIXME: since the namespace is now ApplicationModel, the name OperationCompletedEventArgs
  // is too generic. Should we rename it?
  {
    DataPackageOperation Operation { get; };

    String AcceptedFormatId { get; };
  }

  /// <summary>
  /// Static string-valued properties corresponding to data format IDs known
  /// to the <see cref="DataPackage"/> system.
  /// </summary>
  [contract(ClipboardContract, 1.0)]
  static runtimeclass StandardDataFormats
  {
    static String Text { get; };
    static String Html { get; };
    static String Rtf { get; };
    static String Bitmap { get; };
    static String StorageItems { get; };

    static String WebLink { get; };
    static String ApplicationLink { get; };

    static String UserActivityJsonArray { get; };
  }
}
