// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace Microsoft.Kozani.ManagerRuntime
{
    [contractversion(1)]
    apicontract ManagerRuntimeContract{};

    [contract(ManagerRuntimeContract, 1)]
    runtimeclass ManagerRuntimeManager
    {
        static ManagerRuntimeManager Create();

        void ActivateRemoteApplication(
            Windows.ApplicationModel.Activation.ActivationKind activationKind,
            String appUserModelId,
            String connectionRdpFilePath,
            UInt32 associatedLocalProcessId, // optional, use 0 if you don't want the remote app lifetime to be tied to the lifetime of an associated local process
            Windows.ApplicationModel.Activation.IActivatedEventArgs args,   // optional - can be nullptr if there are no activatedEventArgs for Launch ActivationKind
            IInspectable statusCallback,     // optional - can be nullptr if the caller does not need status update callbacks
            String additionalSettingsFilePath   // optional - can be empty String if the additional settings file does not exist
            );
    };
}
