//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVDAppAttachValidate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ScriptResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AVDAppAttachValidate.ScriptResources", typeof(ScriptResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to param(
        ///        [Parameter(Mandatory=$false)]
        ///        [string] $accessToken,
        ///
        ///        [Parameter(Mandatory=$false)]
        ///        [string] $emailId,
        ///
        ///        [Parameter(Mandatory=$false)]
        ///        [string] $resourceGroupName,
        ///
        ///        [Parameter(Mandatory=$false)]
        ///        [string] $subscriptionId,
        ///
        ///        [Parameter(Mandatory=$false)]
        ///        [string] $storageAccountName,
        ///
        ///        [Parameter(Mandatory=$false)]
        ///        [string] $fileshareName,
        ///
        ///        [Parameter(Mandatory=$false)]
        ///        [stri [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AzureFileShareScript {
            get {
                return ResourceManager.GetString("AzureFileShareScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to param(
        ///        [Parameter(Mandatory=$false)]
        ///        [string] $powershellIsRunningAsAdmin,
        ///
        ///        [Parameter(Mandatory=$false)]
        ///        [string] $powershellIsNotRunningAsAdmin
        ///    )
        ///try{
        ///    
        ///    if(-not ($powershellIsRunningAsAdmin -and $powershellIsNotRunningAsAdmin)){
        ///        throw &quot;Mandatory parameters are missing in the script&quot;
        ///    }
        ///
        ///    # Check if Powershell has admin priviledges
        ///    if(-not ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsIn [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EnvironmentCheckScript {
            get {
                return ResourceManager.GetString("EnvironmentCheckScript", resourceCulture);
            }
        }
    }
}
