// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

import "oaidl.idl";
import "ocidl.idl";

[object]
[uuid(d04de8b9-d137-49b8-b5cc-e0fb15128471)]
[pointer_default(unique)]
interface IKozaniManager : IUnknown
{
    HRESULT Initialize();

    HRESULT Shutdown();
};
