// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

import "oaidl.idl";
import "ocidl.idl";

[object]
[uuid(867c396f-8702-4b95-99ec-fd38570410d7)]
[pointer_default(unique)]
interface IKozaniManager : IUnknown
{
    HRESULT Initialize();

    HRESULT Shutdown();
};
