// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

import "oaidl.idl";
import "ocidl.idl";

[object]
[uuid(4e33e4b4-15b1-4db1-946f-d82dc2fddb5d)]
[pointer_default(unique)]
interface IKozaniManager : IUnknown
{
    HRESULT Initialize();

    HRESULT Shutdown();
};
