// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

#include <TerminalVelocityFeatures-DeploymentAPI.h>

namespace Microsoft.Windows.ApplicationModel.WindowsAppRuntime
{
    [contractversion(4)]
    apicontract DeploymentContract{};

    /// Represents the current Deployment status of the WindowsAppRuntime
    [contract(DeploymentContract, 1)]
    enum DeploymentStatus
    {
        Unknown = 0,
        Ok,
        PackageInstallRequired,
        PackageInstallFailed,
        [feature(Feature_DeploymentRepair)]
        [contract(DeploymentContract, 4)]
        PackageRepairFailed,
    };

    /// Represents the result of a Deployment Manager method.
    [contract(DeploymentContract, 1)]
    runtimeclass DeploymentResult
    {
        DeploymentResult(DeploymentStatus status, HRESULT extendedError);

        /// Returns the DeploymentStatus of the result.
        DeploymentStatus Status { get; };

        /// Returns the first encountered error if there was an error or S_OK if no error.
        HRESULT ExtendedError{ get; };
    };

    /// This object is used to specify deployment options to apply when using DeploymentManager's
    /// Initialize method
    [contract(DeploymentContract, 2)]
    runtimeclass DeploymentInitializeOptions
    {
        DeploymentInitializeOptions();

        /// Gets or sets a value that indicates whether the processes associated with the
        /// WindowsAppSDK Main and Singleton packages will be shut down forcibly if they are
        /// currently in use, when registering the WinAppSDK packages.
        Boolean ForceDeployment;

        /// If not successful show UI
        [contract(DeploymentContract, 3)]
        Boolean OnErrorShowUI;
    };

    /// Used to query deployment information for WindowsAppRuntime
    [contract(DeploymentContract, 1)]
    static runtimeclass DeploymentManager
    {
        /// Returns the current deployment status of the current package's Windows App Runtime.
        static DeploymentResult GetStatus();

        /// Checks the status of the WindowsAppRuntime of the current package and attempts to
        /// register any missing WinAppSDK packages.
        [overload("Initialize")]
        static DeploymentResult Initialize();

        /// Checks the status of the WindowsAppRuntime of the current package and attempts to
        /// register any missing WinAppSDK packages, while applying the DeploymentInitializeOptions
        /// passed in.
        [contract(DeploymentContract, 2)]
        [overload("Initialize")]
        static DeploymentResult Initialize(Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentInitializeOptions deploymentInitializeOptions);

        /// Checks the status of the WindowsAppRuntime of the current package and attempts to
        /// repair already installed WinAppSDK packages.
        [feature(Feature_DeploymentRepair)]
        [contract(DeploymentContract, 4)]
        static DeploymentResult Repair();
    };
}
