// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

#pragma once

// This header defines the packages included in the installer.
// By default, the project will use test packages built for verification of this installer.

// For building the installer with non-test packages, include a "windowsappruntime_definitions_override.h" file.
// If present, the override header will be loaded to change the package definitions such as the path.
// Preprocessor definitions used in the override header must be supported by the resource compiler.

// Override header file example:
//
// #pragma once
//
// #undef WINDOWSAPPRUNTIME_FRAMEWORK_X86_PATH
// #define WINDOWSAPPRUNTIME_FRAMEWORK_X86_PATH "custompackages\\my_custom_x86_framework.appx"
//

// Each package has a package definition listed below.
// Names for macros are intentionally kept short due to resource compiler length limitations.

// x86 Framework
#define WINDOWSAPPRUNTIME_FRAMEWORK_X86_ID L"WINDOWSAPPRUNTIME_FWPACKAGE_X86"
#define WINDOWSAPPRUNTIME_FRAMEWORK_X86_RCID WINDOWSAPPRUNTIME_FWPACKAGE_X86
#define WINDOWSAPPRUNTIME_FRAMEWORK_X86_TYPE L"PACKAGE"
#define WINDOWSAPPRUNTIME_FRAMEWORK_X86_RCTYPE PACKAGE
#define WINDOWSAPPRUNTIME_FRAMEWORK_X86_BEHAVIOR DeploymentBehavior::Default
#ifndef WINDOWSAPPRUNTIME_FRAMEWORK_X86_PATH
    #define WINDOWSAPPRUNTIME_FRAMEWORK_X86_PATH "..\\test\\testpackages\\framework_x86.msix"
#endif

// x64 Framework
#define WINDOWSAPPRUNTIME_FRAMEWORK_X64_ID L"WINDOWSAPPRUNTIME_FWPACKAGE_X64"
#define WINDOWSAPPRUNTIME_FRAMEWORK_X64_RCID WINDOWSAPPRUNTIME_FWPACKAGE_X64
#define WINDOWSAPPRUNTIME_FRAMEWORK_X64_TYPE L"PACKAGE"
#define WINDOWSAPPRUNTIME_FRAMEWORK_X64_RCTYPE PACKAGE
#define WINDOWSAPPRUNTIME_FRAMEWORK_X64_BEHAVIOR DeploymentBehavior::Default
#ifndef WINDOWSAPPRUNTIME_FRAMEWORK_X64_PATH
    #define WINDOWSAPPRUNTIME_FRAMEWORK_X64_PATH "..\\test\\testpackages\\framework_x64.msix"
#endif

// arm64 Framework
#define WINDOWSAPPRUNTIME_FRAMEWORK_ARM64_ID L"WINDOWSAPPRUNTIME_FWPACKAGE_ARM64"
#define WINDOWSAPPRUNTIME_FRAMEWORK_ARM64_RCID WINDOWSAPPRUNTIME_FWPACKAGE_ARM64
#define WINDOWSAPPRUNTIME_FRAMEWORK_ARM64_TYPE L"PACKAGE"
#define WINDOWSAPPRUNTIME_FRAMEWORK_ARM64_RCTYPE PACKAGE
#define WINDOWSAPPRUNTIME_FRAMEWORK_ARM64_BEHAVIOR DeploymentBehavior::Default
#ifndef WINDOWSAPPRUNTIME_FRAMEWORK_ARM64_PATH
    #define WINDOWSAPPRUNTIME_FRAMEWORK_ARM64_PATH "..\\test\\testpackages\\framework_arm64.msix"
#endif

// x86 Main
#define WINDOWSAPPRUNTIME_MAIN_X86_ID L"WINDOWSAPPRUNTIME_MAINPACKAGE_X86"
#define WINDOWSAPPRUNTIME_MAIN_X86_RCID WINDOWSAPPRUNTIME_MAINPACKAGE_X86
#define WINDOWSAPPRUNTIME_MAIN_X86_TYPE L"PACKAGE"
#define WINDOWSAPPRUNTIME_MAIN_X86_RCTYPE PACKAGE
#define WINDOWSAPPRUNTIME_MAIN_X86_BEHAVIOR DeploymentBehavior::Default
#ifndef WINDOWSAPPRUNTIME_MAIN_X86_PATH
    #define WINDOWSAPPRUNTIME_MAIN_X86_PATH "..\\test\\testpackages\\main_x86.msix"
#endif

// x64 Main
#define WINDOWSAPPRUNTIME_MAIN_X64_ID L"WINDOWSAPPRUNTIME_MAINPACKAGE_X64"
#define WINDOWSAPPRUNTIME_MAIN_X64_RCID WINDOWSAPPRUNTIME_MAINPACKAGE_X64
#define WINDOWSAPPRUNTIME_MAIN_X64_TYPE L"PACKAGE"
#define WINDOWSAPPRUNTIME_MAIN_X64_RCTYPE PACKAGE
#define WINDOWSAPPRUNTIME_MAIN_X64_BEHAVIOR DeploymentBehavior::Default
#ifndef WINDOWSAPPRUNTIME_MAIN_X64_PATH
    #define WINDOWSAPPRUNTIME_MAIN_X64_PATH "..\\test\\testpackages\\main_x64.msix"
#endif

// arm64 Main
#define WINDOWSAPPRUNTIME_MAIN_ARM64_ID L"WINDOWSAPPRUNTIME_MAINPACKAGE_ARM64"
#define WINDOWSAPPRUNTIME_MAIN_ARM64_RCID WINDOWSAPPRUNTIME_MAINPACKAGE_ARM64
#define WINDOWSAPPRUNTIME_MAIN_ARM64_TYPE L"PACKAGE"
#define WINDOWSAPPRUNTIME_MAIN_ARM64_RCTYPE PACKAGE
#define WINDOWSAPPRUNTIME_MAIN_ARM64_BEHAVIOR DeploymentBehavior::Default
#ifndef WINDOWSAPPRUNTIME_MAIN_ARM64_PATH
    #define WINDOWSAPPRUNTIME_MAIN_ARM64_PATH "..\\test\\testpackages\\main_arm64.msix"
#endif

// license Main
#define WINDOWSAPPRUNTIME_MAIN_LICENSE_ID L"WINDOWSAPPRUNTIME_MAINPACKAGE_LICENSE"
#define WINDOWSAPPRUNTIME_MAIN_LICENSE_RCID WINDOWSAPPRUNTIME_MAINPACKAGE_LICENSE
#define WINDOWSAPPRUNTIME_MAIN_LICENSE_TYPE L"LICENSE"
#define WINDOWSAPPRUNTIME_MAIN_LICENSE_RCTYPE LICENSE
#ifndef WINDOWSAPPRUNTIME_MAIN_LICENSE_PATH
    #define WINDOWSAPPRUNTIME_MAIN_LICENSE_PATH "..\\test\\testpackages\\main_license.xml"
#endif

// x86 Singleton
#define WINDOWSAPPRUNTIME_SINGLETON_X86_ID L"WINDOWSAPPRUNTIME_SINGLETONPACKAGE_X86"
#define WINDOWSAPPRUNTIME_SINGLETON_X86_RCID WINDOWSAPPRUNTIME_SINGLETONPACKAGE_X86
#define WINDOWSAPPRUNTIME_SINGLETON_X86_TYPE L"PACKAGE"
#define WINDOWSAPPRUNTIME_SINGLETON_X86_RCTYPE PACKAGE
#define WINDOWSAPPRUNTIME_SINGLETON_X86_BEHAVIOR DeploymentBehavior::Default
#ifndef WINDOWSAPPRUNTIME_SINGLETON_X86_PATH
    #define WINDOWSAPPRUNTIME_SINGLETON_X86_PATH "..\\test\\testpackages\\singleton_x86.msix"
#endif

// x64 Singleton
#define WINDOWSAPPRUNTIME_SINGLETON_X64_ID L"WINDOWSAPPRUNTIME_SINGLETONPACKAGE_X64"
#define WINDOWSAPPRUNTIME_SINGLETON_X64_RCID WINDOWSAPPRUNTIME_SINGLETONPACKAGE_X64
#define WINDOWSAPPRUNTIME_SINGLETON_X64_TYPE L"PACKAGE"
#define WINDOWSAPPRUNTIME_SINGLETON_X64_RCTYPE PACKAGE
#define WINDOWSAPPRUNTIME_SINGLETON_X64_BEHAVIOR DeploymentBehavior::Default
#ifndef WINDOWSAPPRUNTIME_SINGLETON_X64_PATH
    #define WINDOWSAPPRUNTIME_SINGLETON_X64_PATH "..\\test\\testpackages\\singleton_x64.msix"
#endif

// arm64 Singleton
#define WINDOWSAPPRUNTIME_SINGLETON_ARM64_ID L"WINDOWSAPPRUNTIME_SINGLETONPACKAGE_ARM64"
#define WINDOWSAPPRUNTIME_SINGLETON_ARM64_RCID WINDOWSAPPRUNTIME_SINGLETONPACKAGE_ARM64
#define WINDOWSAPPRUNTIME_SINGLETON_ARM64_TYPE L"PACKAGE"
#define WINDOWSAPPRUNTIME_SINGLETON_ARM64_RCTYPE PACKAGE
#define WINDOWSAPPRUNTIME_SINGLETON_ARM64_BEHAVIOR DeploymentBehavior::Default
#ifndef WINDOWSAPPRUNTIME_SINGLETON_ARM64_PATH
    #define WINDOWSAPPRUNTIME_SINGLETON_ARM64_PATH "..\\test\\testpackages\\singleton_arm64.msix"
#endif

// license Singleton
#define WINDOWSAPPRUNTIME_SINGLETON_LICENSE_ID L"WINDOWSAPPRUNTIME_SINGLETONPACKAGE_LICENSE"
#define WINDOWSAPPRUNTIME_SINGLETON_LICENSE_RCID WINDOWSAPPRUNTIME_SINGLETONPACKAGE_LICENSE
#define WINDOWSAPPRUNTIME_SINGLETON_LICENSE_TYPE L"LICENSE"
#define WINDOWSAPPRUNTIME_SINGLETON_LICENSE_RCTYPE LICENSE
#ifndef WINDOWSAPPRUNTIME_SINGLETON_LICENSE_PATH
    #define WINDOWSAPPRUNTIME_SINGLETON_LICENSE_PATH "..\\test\\testpackages\\singleton_license.xml"
#endif

// x86 DDLM
#define WINDOWSAPPRUNTIME_DDLM_X86_ID L"WINDOWSAPPRUNTIME_DDLMPACKAGE_X86"
#define WINDOWSAPPRUNTIME_DDLM_X86_RCID WINDOWSAPPRUNTIME_DDLMPACKAGE_X86
#define WINDOWSAPPRUNTIME_DDLM_X86_TYPE L"PACKAGE"
#define WINDOWSAPPRUNTIME_DDLM_X86_RCTYPE PACKAGE
#define WINDOWSAPPRUNTIME_DDLM_X86_BEHAVIOR DeploymentBehavior::Framework
#ifndef WINDOWSAPPRUNTIME_DDLM_X86_PATH
    #define WINDOWSAPPRUNTIME_DDLM_X86_PATH "..\\test\\testpackages\\ddlm_x86.msix"
#endif

// x64 DDLM
#define WINDOWSAPPRUNTIME_DDLM_X64_ID L"WINDOWSAPPRUNTIME_DDLMPACKAGE_X64"
#define WINDOWSAPPRUNTIME_DDLM_X64_RCID WINDOWSAPPRUNTIME_DDLMPACKAGE_X64
#define WINDOWSAPPRUNTIME_DDLM_X64_TYPE L"PACKAGE"
#define WINDOWSAPPRUNTIME_DDLM_X64_RCTYPE PACKAGE
#define WINDOWSAPPRUNTIME_DDLM_X64_BEHAVIOR DeploymentBehavior::Framework
#ifndef WINDOWSAPPRUNTIME_DDLM_X64_PATH
    #define WINDOWSAPPRUNTIME_DDLM_X64_PATH "..\\test\\testpackages\\ddlm_x64.msix"
#endif

// arm64 DDLM
#define WINDOWSAPPRUNTIME_DDLM_ARM64_ID L"WINDOWSAPPRUNTIME_DDLMPACKAGE_ARM64"
#define WINDOWSAPPRUNTIME_DDLM_ARM64_RCID WINDOWSAPPRUNTIME_DDLMPACKAGE_ARM64
#define WINDOWSAPPRUNTIME_DDLM_ARM64_TYPE L"PACKAGE"
#define WINDOWSAPPRUNTIME_DDLM_ARM64_RCTYPE PACKAGE
#define WINDOWSAPPRUNTIME_DDLM_ARM64_BEHAVIOR DeploymentBehavior::Framework
#ifndef WINDOWSAPPRUNTIME_DDLM_ARM64_PATH
    #define WINDOWSAPPRUNTIME_DDLM_ARM64_PATH "..\\test\\testpackages\\ddlm_arm64.msix"
#endif


// Package Inclusion
// Each package has a package list entry which defines its inclusion in packages.h and the .rc script.
// To not include a package, undefine the *_LISTENTRY and *_RCENTRY entries. At least one package must be included.

#define WINDOWSAPPRUNTIME_FRAMEWORK_X86_LISTENTRY { WINDOWSAPPRUNTIME_FRAMEWORK_X86_ID, WINDOWSAPPRUNTIME_FRAMEWORK_X86_TYPE, WINDOWSAPPRUNTIME_FRAMEWORK_X86_BEHAVIOR },
#define WINDOWSAPPRUNTIME_FRAMEWORK_X86_RCENTRY WINDOWSAPPRUNTIME_FRAMEWORK_X86_RCID WINDOWSAPPRUNTIME_FRAMEWORK_X86_RCTYPE WINDOWSAPPRUNTIME_FRAMEWORK_X86_PATH

#define WINDOWSAPPRUNTIME_FRAMEWORK_X64_LISTENTRY  { WINDOWSAPPRUNTIME_FRAMEWORK_X64_ID, WINDOWSAPPRUNTIME_FRAMEWORK_X64_TYPE, WINDOWSAPPRUNTIME_FRAMEWORK_X64_BEHAVIOR },
#define WINDOWSAPPRUNTIME_FRAMEWORK_X64_RCENTRY WINDOWSAPPRUNTIME_FRAMEWORK_X64_RCID WINDOWSAPPRUNTIME_FRAMEWORK_X64_RCTYPE WINDOWSAPPRUNTIME_FRAMEWORK_X64_PATH

#define WINDOWSAPPRUNTIME_FRAMEWORK_ARM64_LISTENTRY { WINDOWSAPPRUNTIME_FRAMEWORK_ARM64_ID, WINDOWSAPPRUNTIME_FRAMEWORK_ARM64_TYPE, WINDOWSAPPRUNTIME_FRAMEWORK_ARM64_BEHAVIOR },
#define WINDOWSAPPRUNTIME_FRAMEWORK_ARM64_RCENTRY WINDOWSAPPRUNTIME_FRAMEWORK_ARM64_RCID WINDOWSAPPRUNTIME_FRAMEWORK_ARM64_RCTYPE WINDOWSAPPRUNTIME_FRAMEWORK_ARM64_PATH

#define WINDOWSAPPRUNTIME_MAIN_X86_LISTENTRY { WINDOWSAPPRUNTIME_MAIN_X86_ID, WINDOWSAPPRUNTIME_MAIN_X86_TYPE, WINDOWSAPPRUNTIME_MAIN_X86_BEHAVIOR },
#define WINDOWSAPPRUNTIME_MAIN_X86_RCENTRY WINDOWSAPPRUNTIME_MAIN_X86_RCID WINDOWSAPPRUNTIME_MAIN_X86_RCTYPE WINDOWSAPPRUNTIME_MAIN_X86_PATH

#define WINDOWSAPPRUNTIME_MAIN_X64_LISTENTRY  { WINDOWSAPPRUNTIME_MAIN_X64_ID, WINDOWSAPPRUNTIME_MAIN_X64_TYPE, WINDOWSAPPRUNTIME_MAIN_X64_BEHAVIOR },
#define WINDOWSAPPRUNTIME_MAIN_X64_RCENTRY WINDOWSAPPRUNTIME_MAIN_X64_RCID WINDOWSAPPRUNTIME_MAIN_X64_RCTYPE WINDOWSAPPRUNTIME_MAIN_X64_PATH

#define WINDOWSAPPRUNTIME_MAIN_ARM64_LISTENTRY { WINDOWSAPPRUNTIME_MAIN_ARM64_ID, WINDOWSAPPRUNTIME_MAIN_ARM64_TYPE, WINDOWSAPPRUNTIME_MAIN_ARM64_BEHAVIOR },
#define WINDOWSAPPRUNTIME_MAIN_ARM64_RCENTRY WINDOWSAPPRUNTIME_MAIN_ARM64_RCID WINDOWSAPPRUNTIME_MAIN_ARM64_RCTYPE WINDOWSAPPRUNTIME_MAIN_ARM64_PATH

#define WINDOWSAPPRUNTIME_SINGLETON_X86_LISTENTRY { WINDOWSAPPRUNTIME_SINGLETON_X86_ID, WINDOWSAPPRUNTIME_SINGLETON_X86_TYPE, WINDOWSAPPRUNTIME_SINGLETON_X86_BEHAVIOR },
#define WINDOWSAPPRUNTIME_SINGLETON_X86_RCENTRY WINDOWSAPPRUNTIME_SINGLETON_X86_RCID WINDOWSAPPRUNTIME_SINGLETON_X86_RCTYPE WINDOWSAPPRUNTIME_SINGLETON_X86_PATH

#define WINDOWSAPPRUNTIME_SINGLETON_X64_LISTENTRY  { WINDOWSAPPRUNTIME_SINGLETON_X64_ID, WINDOWSAPPRUNTIME_SINGLETON_X64_TYPE, WINDOWSAPPRUNTIME_SINGLETON_X64_BEHAVIOR },
#define WINDOWSAPPRUNTIME_SINGLETON_X64_RCENTRY WINDOWSAPPRUNTIME_SINGLETON_X64_RCID WINDOWSAPPRUNTIME_SINGLETON_X64_RCTYPE WINDOWSAPPRUNTIME_SINGLETON_X64_PATH

#define WINDOWSAPPRUNTIME_SINGLETON_ARM64_LISTENTRY { WINDOWSAPPRUNTIME_SINGLETON_ARM64_ID, WINDOWSAPPRUNTIME_SINGLETON_ARM64_TYPE, WINDOWSAPPRUNTIME_SINGLETON_ARM64_BEHAVIOR },
#define WINDOWSAPPRUNTIME_SINGLETON_ARM64_RCENTRY WINDOWSAPPRUNTIME_SINGLETON_ARM64_RCID WINDOWSAPPRUNTIME_SINGLETON_ARM64_RCTYPE WINDOWSAPPRUNTIME_SINGLETON_ARM64_PATH

#define WINDOWSAPPRUNTIME_DDLM_X86_LISTENTRY { WINDOWSAPPRUNTIME_DDLM_X86_ID, WINDOWSAPPRUNTIME_DDLM_X86_TYPE, WINDOWSAPPRUNTIME_DDLM_X86_BEHAVIOR },
#define WINDOWSAPPRUNTIME_DDLM_X86_RCENTRY WINDOWSAPPRUNTIME_DDLM_X86_RCID WINDOWSAPPRUNTIME_DDLM_X86_RCTYPE WINDOWSAPPRUNTIME_DDLM_X86_PATH

#define WINDOWSAPPRUNTIME_DDLM_X64_LISTENTRY  { WINDOWSAPPRUNTIME_DDLM_X64_ID, WINDOWSAPPRUNTIME_DDLM_X64_TYPE, WINDOWSAPPRUNTIME_DDLM_X64_BEHAVIOR },
#define WINDOWSAPPRUNTIME_DDLM_X64_RCENTRY WINDOWSAPPRUNTIME_DDLM_X64_RCID WINDOWSAPPRUNTIME_DDLM_X64_RCTYPE WINDOWSAPPRUNTIME_DDLM_X64_PATH

#define WINDOWSAPPRUNTIME_DDLM_ARM64_LISTENTRY { WINDOWSAPPRUNTIME_DDLM_ARM64_ID, WINDOWSAPPRUNTIME_DDLM_ARM64_TYPE, WINDOWSAPPRUNTIME_DDLM_ARM64_BEHAVIOR },
#define WINDOWSAPPRUNTIME_DDLM_ARM64_RCENTRY WINDOWSAPPRUNTIME_DDLM_ARM64_RCID WINDOWSAPPRUNTIME_DDLM_ARM64_RCTYPE WINDOWSAPPRUNTIME_DDLM_ARM64_PATH

// License Inclusion

// NOTE: We default to assuming a Main license file and no Singleton license file for inner-loop purposes.
//       The build pipeline will define expected values in windowsappruntime_definitions_override.h for official builds.

#define WINDOWSAPPRUNTIME_MAIN_LICENSE_LISTENTRY { WINDOWSAPPRUNTIME_MAIN_LICENSE_ID, WINDOWSAPPRUNTIME_MAIN_LICENSE_TYPE },
#define WINDOWSAPPRUNTIME_MAIN_LICENSE_RCENTRY WINDOWSAPPRUNTIME_MAIN_LICENSE_RCID WINDOWSAPPRUNTIME_MAIN_LICENSE_RCTYPE WINDOWSAPPRUNTIME_MAIN_LICENSE_PATH

#undef WINDOWSAPPRUNTIME_SINGLETON_LICENSE_LISTENTRY
#undef WINDOWSAPPRUNTIME_SINGLETON_LICENSE_RCENTRY


// This is defined in the vcxproj based on existence of the header in the same directory.
// It is defined in both the c compiler preprocessor definitions and the resource compiler preprocessor definitions.
#ifdef USE_DEFINITIONS_OVERRIDE_HEADER
    #include "windowsappruntime_definitions_override.h"
#endif
