// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace Microsoft.Windows.ApplicationModel.Background
{
    [contractversion(1)]
    apicontract BackgroundTaskContract{};

    [contract(BackgroundTaskContract, 1)]
    runtimeclass BackgroundTaskBuilder
    {
        BackgroundTaskBuilder();

        void SetTrigger(
                Windows.ApplicationModel.Background.IBackgroundTrigger trigger
            );
        void SetTaskEntryPointClsId(
                GUID clsId
            );

        String Name{ set; get; };

        [return_name("task")]
            Windows.ApplicationModel.Background.BackgroundTaskRegistration Register();
        [return_name("task")]
            Windows.ApplicationModel.Background.BackgroundTaskRegistration Register(String name);
    }
}
