// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

#include <TerminalVelocityFeatures-EnvironmentManager.h>

namespace Microsoft.Windows.System
{
    [contractversion(2)]
    apicontract EnvironmentManagerContract{};

    [contract(EnvironmentManagerContract, 1)]
    runtimeclass EnvironmentManager
    {
        static EnvironmentManager GetForProcess();
        static EnvironmentManager GetForUser();
        static EnvironmentManager GetForMachine();

        static Boolean IsSupported{ get; };

        IMapView<String, String> GetEnvironmentVariables();
        String GetEnvironmentVariable(String name);
        void SetEnvironmentVariable(String name, String value);

        // Path manipulation
        void AppendToPath(String path);
        void RemoveFromPath(String path);

        // PathExt Manipulation
        void AddExecutableFileExtension(String pathExt);
        void RemoveExecutableFileExtension(String pathExt);

        [contract(EnvironmentManagerContract, 2)]
        Boolean AreChangesTracked{ get; };
    }
}
