// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

namespace Microsoft.Windows.System
{
    [experimental]
    runtimeclass EnvironmentManager
    {
        [experimental]
        static EnvironmentManager GetForProcess();

        [experimental]
        static EnvironmentManager GetForUser();

        [experimental]
        static EnvironmentManager GetForMachine();

        [experimental]
        static Boolean IsSupported{ get; };

        [experimental]
        IMapView<String, String> GetEnvironmentVariables();

        [experimental]
        String GetEnvironmentVariable(String name);

        [experimental]
        void SetEnvironmentVariable(String name, String value);

        // Path manipulation
        [experimental]
        void AppendToPath(String path);

        [experimental]
        void RemoveFromPath(String path);

        // PathExt Manipulation
        [experimental]
        void AddExecutableFileExtension(String pathExt);

        [experimental]
        void RemoveExecutableFileExtension(String pathExt);
    }
}
