// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

namespace Microsoft.Windows.ApplicationModel.WindowsAppRuntime
{
    [contractversion(1)]
    apicontract RuntimeCompatibilityContract {};

    /// The set of servicing changes that can be disabled.
    [contract(RuntimeCompatibilityContract, 1)]
    enum RuntimeCompatibilityChange
    {
        None = 0, /// do not use this value

        // 2.1.0
        ItemTemplateWrapper_RecyclePoolLeak = 61574373,
        Animation_FixImplicitHideAnimationCrash = 61760863,
        TitleBar_ContentDragRegions = 61831627,
        Popup_WindowedPopupOverrideScale = 61847252,
        UIAffinityReleaseQueue_PauseDispatchDuringCleanup = 61855278,
        GetModuleHandle_FixAmbiguousModuleLookup = 62040515,
        PackageManager_FixCrash = 62056332,
        ModelInitialization_GetReadyStateAvailabilityGuard = 62056572,
        WindowsML_MultiEpPerPackage = 62083086,
        LanguageModelInsights_GetPartialResultLatency = 62100233,
        WindowsML_FrameworkEpEnumeration = 62100797,
        WindowsML_EpSelectionMode = 62100876,
        UniformGridLayout_GetItemsPerLineDivideByZero = 62147120,

        // 2.2.0
        ApplicationData_GetForUnpackaged = 61684930,
        InputPointerSource_PointerCancelCrashFix = 61854090,
        RenderTargetBitmap_PreCommitCrashOnTreeLeave = 62216616,
        ScrollView_HideIndicatorsTimerUseAfterFree = 62255131,
        ThemeSettings_OffThreadDestructorFix = 62276145,
        MRTCore_SparsePackagedPriFallback = 62382643,
        GetPeerPrivate_UseAfterFree = 62422195,
        WindowsMLFlatCCatalog_CallbackStringOwnership = 62440888,
        WindowsML_ComRundownFix = 62440888,
        WindowsML_ComInitializationFix = 62440888,

        // 2.3.0
        CPopupRoot_ReplayPointerUpdateCrash = 62393567,
        XamlIslandRoot_UiaTeardownReentrancyCrash = 62406051,
        ModernCollectionBasePanel_StaleViewportAnchorRecycle = 62434240,
        Popup_RemoveChildIdempotentWhenClosing = 62434371,
        UIAWindow_PauseNewDispatchOnDisconnectProviders = 62434372,
        CascadingMenuHelper_DelayOpenTimerTickAfterUnload = 62434373,
        AcrylicBrush_InitializePropertyInMarkup = 62471884,
        Xaml_ReserveVectorSpace = 62542953,
        XamlUICommand_LightweightBindings = 62639407,
        Xaml_DefaultStyleOptimizations = 62644600,
        Xaml_ThemeResourceUseResourceKeys = 62645877,
        Xaml_FasterResourceDictionary = 62646974,
        Xaml_CachedTypeChecks = 62659855,
        Xaml_FasterXbfIntLoading = 62673714,
        Xaml_ActivationFactoryFastPaths = 62676756,
        XamlUICommand_SkipEmptyKeyboardAcceleratorBinding = 62676766,
        Xaml_ReduceThemeResourceLookupHashing = 62676773,
        RefreshRateInfo_RemovePowerNotification = 62688041,
        ApplicationData_GetForUnpackaged_LocalSettings = 62698635,
        CustomMetadataTypes_InvalidateUseAfterFree = 62724527,
        CPopup_OpenSetFocusReentrancy = 62724733,
        MediaPlayerPresenter_DeviceLostCrash = 62724906,
        HWBuildGlyphRunTextures_DeviceGuardScope = 62725196,
        FocusRectManager_FindFocusRectHostCrash = 62725364,
        Xaml_EagerDeviceRemovedEventRegistration = 62726703,
        XamlSettings_OptionalChangesApi = 62738389,
        UniversalBGTask_RunCrash = 62755661,
        Xaml_OptimizedCommandBarInitialization = 62759377,
        Flyout_SidePlacementFlipUpAlignmentFix = 62771256,
        LanguageModel_StructuredJsonOutput = 62774942,
        Xaml_OptimizedCommandBarFlyoutUpdateCommands = 62776273,
        XamlInit_GetMuxVersionCompileTime = 62779870,
        Xaml_IconNoGridOptimization = 62784965,
        UniformGridLayoutFlowLayout_OnItemsChangedNullLayoutStateCrash = 62786355,
        Xaml_DeferStylePropertySetters = 62789076,
        Xaml_LoadDeferredResourceOptimization = 62818033,
        Xaml_DeferContextFlyoutInit = 62833838,
        Xaml_DelayApplyStylesAfterCreationComplete = 62847209,
        Xaml_ReserveTrackerCollectionSpace = 62849414,
        WindowsML_ExecutionProviderEnumerationUpdate = 62865780,
        CompositionEngine_API = 62917618,
        WindowsServices_GetKeyboardModifiersStateRace = 62927180,
        VideoSuperResolution_HardwareDetection = 62934326,

        // 2.3.3
        InputPointerSource_DepartingScrollInputCrashFix = 62785439,
        StoragePickers_RestoreFocusAfterDialogCloses = 63006068,
        ResourceManager_RestoreDefaultFallbackPath = 63048673,
        InputPointerSource_OSHaptics = 63096865,
        WindowsAppRuntime_BaseDirectoryIsolation = 63098302,
        AppContentSearchNewAPI_LafCheck = 63264582,
        LanguageModelLanguageDetectionStatus = 63293066,
    };

    /// Represents a version of the Windows App Runtime.
    [contract(RuntimeCompatibilityContract, 1)]
    struct WindowsAppRuntimeVersion
    {
        UInt32 Major;
        UInt32 Minor;
        UInt32 Patch;
    };

    /// This object is used by the app to configure any desired compatibility options
    /// for Windows App Runtime behavior of changes added in servicing updates. This
    /// object is only used to set the runtime behavior and can't be used to query the
    /// applied options.
    [contract(RuntimeCompatibilityContract, 1)]
    runtimeclass RuntimeCompatibilityOptions
    {
        RuntimeCompatibilityOptions();

        /// An optional patch level to use if the runtime version matches the major.minor version.
        WindowsAppRuntimeVersion PatchLevel1 { get; set; };

        /// An optional patch level to use if the runtime version matches the major.minor version.
        WindowsAppRuntimeVersion PatchLevel2 { get; set; };

        /// An optional list of specific servicing changes to disable.
        IVector<RuntimeCompatibilityChange> DisabledChanges{ get; };

        /// Apply the compatibility options to the runtime.
        void Apply();
    }
}
