// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

namespace Microsoft.Windows.ApplicationModel.WindowsAppRuntime
{
    [contractversion(1)]
    apicontract RuntimeCompatibilityContract {};

    /// The set of servicing changes that can be disabled.
    [contract(RuntimeCompatibilityContract, 1)]
    enum RuntimeCompatibilityChange
    {
        None = 0, /// do not use this value

        // 1.8.3
        OrientedVirtualizingPanel_FixBoundsOverflow = 59890419,

        // 1.8.4
        StoragePickers_PreserveFileTypeChoicesInsertionOrder = 60245168,
        StoragePickers_DisplayFileTypeFilterNames = 60245660,
        StoragePickers_DoNotTruncateExistingFileOnSave = 60257559,
        FixCreateIconElementRendering = 60408488,

        // 1.8.5
        InputNonClientPointerSource_PropagateWindowPosChangedMessage = 60326952,
        XamlRoot_FixGetHostWindowInNestedIslands = 60697780,
        DeploymentManager_PackageDowngradeFix = 60760194,
        DwmCoreI_ShutdownManipulationCrash = 60823930,
        ModelInitialization_Insights = 60909827,
        ModelInitialization_KnownExceptions = 60910847,

        // 1.8.6
        AppLifecycle_SharedMemoryRedirectionQueueFix = 60972838,
    };

    /// Represents a version of the Windows App Runtime.
    [contract(RuntimeCompatibilityContract, 1)]
    struct WindowsAppRuntimeVersion
    {
        UInt32 Major;
        UInt32 Minor;
        UInt32 Patch;
    };

    /// This object is used by the app to configure any desired compatibility options
    /// for Windows App Runtime behavior of changes added in servicing updates. This
    /// object is only used to set the runtime behavior and can't be used to query the
    /// applied options.
    [contract(RuntimeCompatibilityContract, 1)]
    runtimeclass RuntimeCompatibilityOptions
    {
        RuntimeCompatibilityOptions();

        /// An optional patch level to use if the runtime version matches the major.minor version.
        WindowsAppRuntimeVersion PatchLevel1 { get; set; };

        /// An optional patch level to use if the runtime version matches the major.minor version.
        WindowsAppRuntimeVersion PatchLevel2 { get; set; };

        /// An optional list of specific servicing changes to disable.
        IVector<RuntimeCompatibilityChange> DisabledChanges{ get; };

        /// Apply the compatibility options to the runtime.
        void Apply();
    }
}
