// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

#include "pch.h"
#include "RuntimeCompatibilityOptions.h"
#include "Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeCompatibilityOptions.g.cpp"
#include "AssemblyInfo.h"
#include <FrameworkUdk/Containment.h>
#include <algorithm>

namespace
{
    // Per-release groups of WinAppSDK contained change IDs. Each group's
    // releaseVersion is the patch release in which the contained change first
    // shipped. RuntimeCompatibilityOptions::Apply() walks the active catalog at
    // startup and pre-prunes (adds to the disabled list) any group whose
    // releaseVersion is greater than the runtime's effective patch level.
    //
    // Release engineering: at branch cut, add a new release group to
    // s_catalogGroupsProd below for any new WINAPPSDK_CHANGE_* IDs that landed
    // in os.2020 FrameworkUdk Containment.h since the previous branch.
    //
    // Servicing engineers do NOT edit this file. They only add the
    // #define WINAPPSDK_CHANGE_FOO id  macro in their component source.
    // Release engineering performs the catalog roll-up.
    //
    // The WinAppSDK_Security pseudo-version is reserved for security fixes -
    // entries in a security group are catalog-tracked but are never
    // auto-disabled by Apply's pre-prune walk because their releaseVersion (0)
    // is never greater than any effective patch level.
    //
    // WinAppSDKReleaseVersion is defined locally here (rather than alongside
    // FrameworkUdk's Containment.h enum) to break the per-release maintenance
    // coupling between FrUdk and Foundation. It is named WinAppSDKReleaseVersion
    // rather than WinAppSDKPatchVersion to avoid colliding with the legacy
    // unscoped enum type name still exposed by older Containment.h headers
    // (renamed there to WinAppSDKPatchVersionDeprecated in newer FrUdk
    // revisions). The scoped enum keeps all release-version constants
    // (WinAppSDK_Latest, WinAppSDK_Security, per-release WinAppSDK_M_m_p)
    // confined to this translation unit; no other component should reference
    // them. WinAppSDKReleaseVersionFromValues mirrors the historical
    // WinAppSDKPatchVersionFromValues encoding (major*1000000 + minor*1000 + patch)
    // so the WindowsAppRuntimeVersion -> WinAppSDKReleaseVersion conversion
    // matches the encoding embedded in each enumerator below.
    constexpr UINT32 WinAppSDKReleaseVersionFromValues(UINT32 major, UINT32 minor, UINT32 patch)
    {
        return (major * 1000000) + (minor * 1000) + patch;
    }

    enum class WinAppSDKReleaseVersion : UINT32
    {
        WinAppSDK_2_1_0 = WinAppSDKReleaseVersionFromValues(2, 1, 0),
        WinAppSDK_2_1_5 = WinAppSDKReleaseVersionFromValues(2, 1, 5),
        WinAppSDK_Latest = 999999999,
        WinAppSDK_Security = 0,
    };

    struct CatalogGroup
    {
        const UINT32* changes;
        UINT32 count;
        WinAppSDKReleaseVersion releaseVersion;
    };

    template <size_t N>
    constexpr CatalogGroup MakeGroup(const UINT32(&arr)[N], WinAppSDKReleaseVersion v)
    {
        return { arr, static_cast<UINT32>(N), v };
    }

    // Test-only catalog. Activated by ContainmentTestInitialize(true). Holds
    // two groups whose releaseVersion straddles the runtime's effective
    // patch level under the default WinAppSDKRuntimeConfiguration (Apply
    // resolves an unspecified patch level to WinAppSDKReleaseVersion::WinAppSDK_Latest).
    // Together they exercise both branches of Apply's pre-prune walk and
    // span the changeId value range so that std::sort (Apply) and
    // std::binary_search (FrUdk worker) are probed at both ends:
    //
    //   * s_enabled_changes_test  is pinned at WinAppSDK_Latest - 1, so
    //     its releaseVersion is NOT greater than the effective patch level.
    //     Apply prunes the group OUT of disabledChanges; these IDs remain
    //     ENABLED at runtime. {1, 2, 3} = small-end IDs that must not
    //     appear in the final sorted disabledChanges set.
    //
    //   * s_disabled_changes_test is pinned at WinAppSDK_Latest + 1, so
    //     its releaseVersion IS greater than the effective patch level.
    //     Apply preserves the group IN disabledChanges; these IDs are
    //     DISABLED at runtime. {0, 99999999} = smallest representable ID
    //     and a high-value sentinel; they must appear in the final sorted
    //     disabledChanges set.
    //
    // Unit tests call IsChangeEnabled<id>() (the 1-argument form) so the
    // catalog pre-prune is the only mechanism that disables changes.
    // Production callsites must not reference 0, 1, 2, 3, or 99999999.
    constexpr UINT32 s_enabled_changes_test[] = { 1, 2, 3 };
    constexpr UINT32 s_disabled_changes_test[] = { 0, 99999999 };
    constexpr CatalogGroup s_catalogGroupsTest[] = {
        MakeGroup(s_enabled_changes_test,
                  static_cast<WinAppSDKReleaseVersion>(static_cast<UINT32>(WinAppSDKReleaseVersion::WinAppSDK_Latest) - 1)),
        MakeGroup(s_disabled_changes_test,
                  static_cast<WinAppSDKReleaseVersion>(static_cast<UINT32>(WinAppSDKReleaseVersion::WinAppSDK_Latest) + 1)),
    };

    // Production catalog for release/2.0-stable. Each per-release group
    // collects the contained change IDs that first shipped in that patch
    // release. Source of truth: os.2020 FrameworkUdk Containment.h
    // (WINAPPSDK_CHANGEID_* macros) and WindowsAppSDK component callsites
    // that #define WINAPPSDK_CHANGEID_* macros inline.
    constexpr UINT32 s_changes_2_1_0[] = {
        61760863, // os.2020: weak ref in implicit animation completion callback
        62040515, // os.2020: see Containment.h for description
        62147120, // os.2020: UniformGridLayout::GetItemsPerLine floor at 1u
    };
    constexpr UINT32 s_changes_2_1_5[] = {
        61684930, // WindowsAppSDK: ApplicationData.GetForUnpackaged()
        61854090, // os.2020: PopulateContactInFrame pen-overrides-touch crash
        62134997, // os.2020: lifted DesktopChildSiteBridge smooth resize
        62276145, // os.2020: ThemeSettings crash on shutdown off-thread
        62382643, // WindowsAppSDK: MRT sparse-packaged module-specific PRI discovery
    };
    constexpr CatalogGroup s_catalogGroupsProd[] = {
        MakeGroup(s_changes_2_1_0, WinAppSDKReleaseVersion::WinAppSDK_2_1_0),
        MakeGroup(s_changes_2_1_5, WinAppSDKReleaseVersion::WinAppSDK_2_1_5),
    };
    constexpr size_t s_catalogGroupsProdCount{ std::size(s_catalogGroupsProd) };

    // Active catalog. ContainmentTestInitialize(bool) swaps these pointers
    // between the production and test catalogs. Apply() reads them at runtime.
    const CatalogGroup* s_catalogGroup{ s_catalogGroupsProd };
    size_t s_catalogGroupCount{ s_catalogGroupsProdCount };
}

STDAPI ContainmentTestInitialize(bool enableTest) noexcept try
{
    if (enableTest)
    {
        s_catalogGroup = s_catalogGroupsTest;
        s_catalogGroupCount = std::size(s_catalogGroupsTest);
    }
    else
    {
        s_catalogGroup = s_catalogGroupsProd;
        s_catalogGroupCount = s_catalogGroupsProdCount;
    }
    return S_OK;
} CATCH_RETURN();

namespace winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::implementation
{
    winrt::Windows::Foundation::Collections::IVector<RuntimeCompatibilityChange> RuntimeCompatibilityOptions::DisabledChanges()
    {
        return m_disabledChanges;
    }

    void RuntimeCompatibilityOptions::Apply()
    {
        WinAppSdk::Containment::WinAppSDKRuntimeConfiguration config;

        // If both patch levels are set to the same major.minor version, error out if the patch versions are different.
        if (m_patchLevel1.Major == m_patchLevel2.Major && m_patchLevel1.Minor == m_patchLevel2.Minor &&
            m_patchLevel1.Major != 0)
        {
            if (m_patchLevel1.Patch != m_patchLevel2.Patch)
            {
                throw hresult_invalid_argument(L"Patch levels should target different Major.Minor versions or match Patch version.");
            }
        }

        // Resolve the effective patch level for catalog pre-prune. This is owned
        // entirely by WinAppSDK now - when the 2.0 branch bumps to a FrUdk that
        // exposes only WinAppSDKPatchVersionDeprecated, FrameworkUdk's
        // Containment_GetChangeEnabled worker will no longer compare against any
        // per-change patch version. The WASDK side is already prepared.
        // A default-initialized WindowsAppRuntimeVersion is {0,0,0}; treat that as
        // "not set" rather than as a request to pin to 0.0.0. (In production builds
        // WINDOWSAPPSDK_RELEASE_MAJOR is > 0 so this case never arises; in dev builds
        // the macro is 0/0 and the unset sentinel would otherwise spuriously match.)
        WinAppSDKReleaseVersion runtimePatchLevel{ WinAppSDKReleaseVersion::WinAppSDK_Latest };
        if (m_patchLevel1.Major == WINDOWSAPPSDK_RELEASE_MAJOR && m_patchLevel1.Minor == WINDOWSAPPSDK_RELEASE_MINOR
            && (m_patchLevel1.Major != 0 || m_patchLevel1.Minor != 0 || m_patchLevel1.Patch != 0))
        {
            // Apply patch level 1
            runtimePatchLevel = static_cast<WinAppSDKReleaseVersion>(
                WinAppSDKReleaseVersionFromValues(m_patchLevel1.Major, m_patchLevel1.Minor, m_patchLevel1.Patch));
        }
        else if (m_patchLevel2.Major == WINDOWSAPPSDK_RELEASE_MAJOR && m_patchLevel2.Minor == WINDOWSAPPSDK_RELEASE_MINOR
            && (m_patchLevel2.Major != 0 || m_patchLevel2.Minor != 0 || m_patchLevel2.Patch != 0))
        {
            // Apply patch level 2
            runtimePatchLevel = static_cast<WinAppSDKReleaseVersion>(
                WinAppSDKReleaseVersionFromValues(m_patchLevel2.Major, m_patchLevel2.Minor, m_patchLevel2.Patch));
        }

        // Mirror the resolved patch level into the ABI-locked
        // WinAppSDKRuntimeConfiguration::patchVersion field as an opaque UINT32
        // cast. Containment_GetChangeEnabled does not read it for change
        // filtering, but Containment_SetConfiguration uses it as part of the
        // identity check that detects attempts to apply a divergent
        // configuration twice from the same process.
        config.patchVersion = static_cast<decltype(config.patchVersion)>(static_cast<UINT32>(runtimePatchLevel));

        // Build the disabled-changes list from two sources:
        //   (1) The app's explicit DisabledChanges list (unchanged behavior).
        //   (2) Catalog pre-pruning: every change whose release is newer than the
        //       effective patch level is treated as disabled, so callsites see
        //       pre-change behavior on patch-pinned runtimes.
        // Duplicates between (1) and (2) are harmless: the FrUdk worker treats
        // disabledChanges as a sorted set and uses set-membership semantics.
        std::vector<UINT32> disabledChanges;
        for (auto changeId : m_disabledChanges)
        {
            // TODO: Telemetry!  Log the changeId that was disabled.
            // UINT32 is used internally for the changeId, so cast from the enum's Int32 to that.
            disabledChanges.push_back(static_cast<UINT32>(changeId));
        }

        for (size_t g = 0; g < s_catalogGroupCount; ++g)
        {
            auto const& group = s_catalogGroup[g];
            if (group.releaseVersion > runtimePatchLevel)
            {
                for (UINT32 i = 0; i < group.count; ++i)
                {
                    disabledChanges.push_back(group.changes[i]);
                }
            }
        }

        // FrameworkUdk's Containment_GetChangeEnabled assumes disabledChanges is
        // sorted ascending so it can use std::binary_search for O(log N) lookups.
        std::sort(disabledChanges.begin(), disabledChanges.end());

        config.disabledChanges = disabledChanges.data();
        config.disabledChangesCount = static_cast<UINT32>(disabledChanges.size());

        HRESULT hr = WinAppSdk::Containment::SetConfiguration(&config);
        if (FAILED(hr))
        {
            if (hr == E_ILLEGAL_STATE_CHANGE)
            {
                throw winrt::hresult_illegal_state_change(L"Configuration already set or locked.");
            }
            winrt::throw_hresult(hr);
        }
    }
}
