//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsAppSDK.Cs.Extension.Dev17 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VSPackage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VSPackage() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsAppSDK.Cs.Extension.Resources.VSPackage", typeof(VSPackage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blank Window.
        /// </summary>
        internal static string _1001 {
            get {
                return ResourceManager.GetString("1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Experimental] Blank Window.
        /// </summary>
        internal static string _1002 {
            get {
                return ResourceManager.GetString("1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A blank window (WinUI)..
        /// </summary>
        internal static string _1003 {
            get {
                return ResourceManager.GetString("1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blank Page.
        /// </summary>
        internal static string _1005 {
            get {
                return ResourceManager.GetString("1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Experimental] Blank Page.
        /// </summary>
        internal static string _1006 {
            get {
                return ResourceManager.GetString("1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A blank page (WinUI)..
        /// </summary>
        internal static string _1007 {
            get {
                return ResourceManager.GetString("1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resource Dictionary.
        /// </summary>
        internal static string _1009 {
            get {
                return ResourceManager.GetString("1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Experimental] Resource Dictionary.
        /// </summary>
        internal static string _1010 {
            get {
                return ResourceManager.GetString("1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An empty, keyed collection of XAML resources (WinUI)..
        /// </summary>
        internal static string _1011 {
            get {
                return ResourceManager.GetString("1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resources File (.resw).
        /// </summary>
        internal static string _1013 {
            get {
                return ResourceManager.GetString("1013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Experimental] Resources File (.resw).
        /// </summary>
        internal static string _1014 {
            get {
                return ResourceManager.GetString("1014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A file for storing string and conditional resources (WinUI)..
        /// </summary>
        internal static string _1015 {
            get {
                return ResourceManager.GetString("1015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Templated Control.
        /// </summary>
        internal static string _1017 {
            get {
                return ResourceManager.GetString("1017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Experimental] Templated Control.
        /// </summary>
        internal static string _1018 {
            get {
                return ResourceManager.GetString("1018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A blank custom control with the appropriate default styling (WinUI)..
        /// </summary>
        internal static string _1019 {
            get {
                return ResourceManager.GetString("1019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Control.
        /// </summary>
        internal static string _1021 {
            get {
                return ResourceManager.GetString("1021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Experimental] User Control.
        /// </summary>
        internal static string _1022 {
            get {
                return ResourceManager.GetString("1022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A blank user control (WinUI)..
        /// </summary>
        internal static string _1023 {
            get {
                return ResourceManager.GetString("1023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WinUI Class Library.
        /// </summary>
        internal static string _1025 {
            get {
                return ResourceManager.GetString("1025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Experimental] WinUI Class Library.
        /// </summary>
        internal static string _1026 {
            get {
                return ResourceManager.GetString("1026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A project for creating a managed class library (.dll) (WinUI)..
        /// </summary>
        internal static string _1027 {
            get {
                return ResourceManager.GetString("1027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WinUI Blank App (Packaged with Windows Application Packaging Project).
        /// </summary>
        internal static string _1029 {
            get {
                return ResourceManager.GetString("1029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Experimental] WinUI Blank App (Packaged with Windows Application Packaging Project).
        /// </summary>
        internal static string _1030 {
            get {
                return ResourceManager.GetString("1030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A project template for creating a WinUI app. A Windows Application Packaging (WAP) project is included to create a MSIX package for side-loading or distribution via the Microsoft Store..
        /// </summary>
        internal static string _1031 {
            get {
                return ResourceManager.GetString("1031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WinUI Blank App (Packaged).
        /// </summary>
        internal static string _1033 {
            get {
                return ResourceManager.GetString("1033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Experimental] WinUI Blank App (Packaged).
        /// </summary>
        internal static string _1034 {
            get {
                return ResourceManager.GetString("1034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A project template for creating a WinUI app along with a MSIX package for side-loading or distribution via the Microsoft Store..
        /// </summary>
        internal static string _1035 {
            get {
                return ResourceManager.GetString("1035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WinUI Unit Test App.
        /// </summary>
        internal static string _1037 {
            get {
                return ResourceManager.GetString("1037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Experimental] WinUI Unit Test App.
        /// </summary>
        internal static string _1038 {
            get {
                return ResourceManager.GetString("1038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A project to create a C# unit test app for WinUI using MSTest..
        /// </summary>
        internal static string _1039 {
            get {
                return ResourceManager.GetString("1039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WinUI Blank App.
        /// </summary>
        internal static string _1040 {
            get {
                return ResourceManager.GetString("1040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A project for creating an empty WinUI app..
        /// </summary>
        internal static string _1041 {
            get {
                return ResourceManager.GetString("1041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Windows Application Packaging Project for WinUI.
        /// </summary>
        internal static string _1042 {
            get {
                return ResourceManager.GetString("1042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A project template that creates MSIX packages containing WinUI applications for side-loading or distribution via the Microsoft Store..
        /// </summary>
        internal static string _1043 {
            get {
                return ResourceManager.GetString("1043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Installing NuGet packages into project....
        /// </summary>
        internal static string _1044 {
            get {
                return ResourceManager.GetString("1044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operation in progress....
        /// </summary>
        internal static string _1045 {
            get {
                return ResourceManager.GetString("1045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing Package Reference(s).
        /// </summary>
        internal static string _1046 {
            get {
                return ResourceManager.GetString("1046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to add references to the following packages for {0}: {1}. Please add package references before building..
        /// </summary>
        internal static string _1047 {
            get {
                return ResourceManager.GetString("1047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [{0}] Unable to add references to the following packages: {1}. This is an environment error. Please add package references before building the project..
        /// </summary>
        internal static string _1048 {
            get {
                return ResourceManager.GetString("1048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage NuGet Packages.
        /// </summary>
        internal static string _1049 {
            get {
                return ResourceManager.GetString("1049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a See error details.
        /// </summary>
        internal static string _1050 {
            get {
                return ResourceManager.GetString("1050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing Package References for {0}:.
        /// </summary>
        internal static string _1051 {
            get {
                return ResourceManager.GetString("1051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please manually add package references before building..
        /// </summary>
        internal static string _1052 {
            get {
                return ResourceManager.GetString("1052", resourceCulture);
            }
        }
    }
}
