//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsAppSDK.Cpp.Extension.Dev17 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VSPackage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VSPackage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsAppSDK.Cpp.Extension.Resources.VSPackage", typeof(VSPackage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank Window.
        /// </summary>
        internal static string _1001 {
            get {
                return ResourceManager.GetString("1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Experimental] Blank Window.
        /// </summary>
        internal static string _1002 {
            get {
                return ResourceManager.GetString("1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A blank window (WinUI)..
        /// </summary>
        internal static string _1003 {
            get {
                return ResourceManager.GetString("1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank Page.
        /// </summary>
        internal static string _1005 {
            get {
                return ResourceManager.GetString("1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Experimental] Blank Page.
        /// </summary>
        internal static string _1006 {
            get {
                return ResourceManager.GetString("1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A blank page (WinUI)..
        /// </summary>
        internal static string _1007 {
            get {
                return ResourceManager.GetString("1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Dictionary.
        /// </summary>
        internal static string _1009 {
            get {
                return ResourceManager.GetString("1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Experimental] Resource Dictionary.
        /// </summary>
        internal static string _1010 {
            get {
                return ResourceManager.GetString("1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty, keyed collection of XAML resources (WinUI)..
        /// </summary>
        internal static string _1011 {
            get {
                return ResourceManager.GetString("1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources File (.resw).
        /// </summary>
        internal static string _1013 {
            get {
                return ResourceManager.GetString("1013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Experimental] Resources File (.resw).
        /// </summary>
        internal static string _1014 {
            get {
                return ResourceManager.GetString("1014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file for storing string and conditional resources (WinUI)..
        /// </summary>
        internal static string _1015 {
            get {
                return ResourceManager.GetString("1015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templated Control.
        /// </summary>
        internal static string _1017 {
            get {
                return ResourceManager.GetString("1017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Experimental] Templated Control.
        /// </summary>
        internal static string _1018 {
            get {
                return ResourceManager.GetString("1018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A blank custom control with the appropriate default styling (WinUI)..
        /// </summary>
        internal static string _1019 {
            get {
                return ResourceManager.GetString("1019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Control.
        /// </summary>
        internal static string _1021 {
            get {
                return ResourceManager.GetString("1021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Experimental] User Control.
        /// </summary>
        internal static string _1022 {
            get {
                return ResourceManager.GetString("1022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A blank user control (WinUI)..
        /// </summary>
        internal static string _1023 {
            get {
                return ResourceManager.GetString("1023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinUI Blank App (Packaged with Windows Application Packaging Project).
        /// </summary>
        internal static string _1025 {
            get {
                return ResourceManager.GetString("1025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Experimental] WinUI Blank App (Packaged with Windows Application Packaging Project).
        /// </summary>
        internal static string _1026 {
            get {
                return ResourceManager.GetString("1026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project template for creating a WinUI app. A Windows Application Packaging (WAP) project is included to create a MSIX package for side-loading or distribution via the Microsoft Store..
        /// </summary>
        internal static string _1027 {
            get {
                return ResourceManager.GetString("1027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinUI Blank App (Packaged).
        /// </summary>
        internal static string _1029 {
            get {
                return ResourceManager.GetString("1029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Experimental] WinUI Blank App (Packaged).
        /// </summary>
        internal static string _1030 {
            get {
                return ResourceManager.GetString("1030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project template for creating a WinUI app along with a MSIX package for side-loading or distribution via the Microsoft Store..
        /// </summary>
        internal static string _1031 {
            get {
                return ResourceManager.GetString("1031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinUI Windows Runtime Component.
        /// </summary>
        internal static string _1033 {
            get {
                return ResourceManager.GetString("1033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Experimental] WinUI Windows Runtime Component (C++/WinRT).
        /// </summary>
        internal static string _1034 {
            get {
                return ResourceManager.GetString("1034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project for creating a C++/WinRT Windows Runtime Component (.winmd) for both desktop and Universal Windows Platform (UWP) apps, based on WinUI..
        /// </summary>
        internal static string _1035 {
            get {
                return ResourceManager.GetString("1035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinUI Unit Test App.
        /// </summary>
        internal static string _1037 {
            get {
                return ResourceManager.GetString("1037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Experimental] WinUI Unit Test App.
        /// </summary>
        internal static string _1038 {
            get {
                return ResourceManager.GetString("1038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project for creating a C++/WinRT unit test app for WinUI using MSTest..
        /// </summary>
        internal static string _1039 {
            get {
                return ResourceManager.GetString("1039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinUI Blank App.
        /// </summary>
        internal static string _1040 {
            get {
                return ResourceManager.GetString("1040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project for creating an empty WinUI app..
        /// </summary>
        internal static string _1041 {
            get {
                return ResourceManager.GetString("1041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Application Packaging Project for WinUI.
        /// </summary>
        internal static string _1042 {
            get {
                return ResourceManager.GetString("1042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project template that creates MSIX packages containing WinUI applications for side-loading or distribution via the Microsoft Store..
        /// </summary>
        internal static string _1043 {
            get {
                return ResourceManager.GetString("1043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing NuGet packages into project....
        /// </summary>
        internal static string _1044 {
            get {
                return ResourceManager.GetString("1044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation in progress....
        /// </summary>
        internal static string _1045 {
            get {
                return ResourceManager.GetString("1045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Package Reference(s).
        /// </summary>
        internal static string _1046 {
            get {
                return ResourceManager.GetString("1046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add references to the following packages for {0}: {1}. Please add package references before building..
        /// </summary>
        internal static string _1047 {
            get {
                return ResourceManager.GetString("1047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Unable to add references to the following packages: {1}. This is an environment error. Please add package references before building the project..
        /// </summary>
        internal static string _1048 {
            get {
                return ResourceManager.GetString("1048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage NuGet Packages.
        /// </summary>
        internal static string _1049 {
            get {
                return ResourceManager.GetString("1049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See error details.
        /// </summary>
        internal static string _1050 {
            get {
                return ResourceManager.GetString("1050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Package References for {0}:.
        /// </summary>
        internal static string _1051 {
            get {
                return ResourceManager.GetString("1051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please manually add package references before building..
        /// </summary>
        internal static string _1052 {
            get {
                return ResourceManager.GetString("1052", resourceCulture);
            }
        }
    }
}
