// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

import "oaidl.idl";
import "ocidl.idl";

#include "../PushNotifications-Constants.h"

[object]
[uuid(PUSHNOTIFICATIONS_FOREGROUNDSINK_CLSID_UUID)]
[pointer_default(unique)]
interface IWpnForegroundSink : IUnknown
{
    HRESULT InvokeAll([in] ULONG length, [in, size_is(length)] byte* data, [out] BOOL* foregroundHandled);
};

[object]
[uuid(PUSHNOTIFICATIONS_FOREGROUNDSINK2_CLSID_UUID)]
[pointer_default(unique)]
interface IWpnForegroundSink2 : IUnknown
{
    HRESULT InvokeAllWithCorrelationVector(
        [in] ULONG length,
        [in, size_is(length)] byte* data,
        [in] LPCWSTR correlationVector,
        [out] BOOL* foregroundHandled);
};

[object]
[uuid(PUSHNOTIFICATIONS_LRP_CLSID_UUID)]
[pointer_default(unique)]
interface INotificationsLongRunningPlatform : IUnknown
{
    HRESULT RegisterLongRunningActivator([in] LPCWSTR processName);

    HRESULT RegisterLongRunningActivatorWithClsid([in] LPCWSTR processName, [in] GUID comServerClsid);

    HRESULT UnregisterLongRunningActivator([in] LPCWSTR processName);

    HRESULT RegisterFullTrustApplication([in] LPCWSTR processName, [in] GUID remoteId, [out] LPWSTR* appId);

    HRESULT UnregisterFullTrustApplication([in] LPCWSTR processName);

    HRESULT RegisterForegroundActivator([in] IWpnForegroundSink* sink, [in] LPCWSTR processName);

    HRESULT UnregisterForegroundActivator([in] LPCWSTR processName);

    HRESULT AddToastRegistrationMapping([in] LPCWSTR processName, [in] LPCWSTR toastAppId);

    HRESULT RemoveToastRegistrationMapping([in] LPCWSTR processName);
};

declare_guid(CLSID_NotificationsLongRunningPlatform, PUSHNOTIFICATIONS_IMPL_CLSID_UUID);
