// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

// THIS FILE IS AUTOMATICALLY GENERATED; DO NOT EDIT IT

// INPUT FILE: dev\Common\TerminalVelocityFeatures-AppNotifications.xml
// OPTIONS: -Channel Experimental -Language C++ -Namespace Microsoft.Windows.AppNotifications

#if defined(__midlrt)
namespace features
{
    feature_name Feature_AppNotifications = { DisabledByDefault, FALSE };
}
#endif // defined(__midlrt)

// Feature constants
#define WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_APPNOTIFICATIONS_FEATURE_APPNOTIFICATIONS_ENABLED 1

#if defined(__cplusplus)

namespace Microsoft::Windows::AppNotifications
{

__pragma(detect_mismatch("ODR_violation_WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_APPNOTIFICATIONS_FEATURE_APPNOTIFICATIONS_ENABLED_mismatch", "AlwaysEnabled"))
struct Feature_AppNotifications
{
    static constexpr bool IsEnabled() { return WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_APPNOTIFICATIONS_FEATURE_APPNOTIFICATIONS_ENABLED == 1; }
};

} // namespace Microsoft.Windows.AppNotifications

#endif // defined(__cplusplus)
