// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

// THIS FILE IS AUTOMATICALLY GENERATED; DO NOT EDIT IT

// INPUT FILE: dev\common\TerminalVelocityFeatures-DeploymentAPI.xml
// OPTIONS: -Channel Experimental -Language C++ -Namespace Microsoft.Windows.PushNotifications

// Feature constants
#define WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_PUSHNOTIFICATIONS_FEATURE_DEPLOYMENTAPI_ENABLED 1

#if defined(__cplusplus)

namespace Microsoft::Windows::PushNotifications
{

__pragma(detect_mismatch("ODR_violation_WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_PUSHNOTIFICATIONS_FEATURE_DEPLOYMENTAPI_ENABLED_mismatch", "AlwaysEnabled"))
struct Feature_DeploymentAPI
{
    static constexpr bool IsEnabled() { return WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_PUSHNOTIFICATIONS_FEATURE_DEPLOYMENTAPI_ENABLED == 1; }
};

} // namespace Microsoft.Windows.PushNotifications

#endif // defined(__cplusplus)
