// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

// THIS FILE IS AUTOMATICALLY GENERATED; DO NOT EDIT IT

// INPUT FILE: dev\Common\TerminalVelocityFeatures-ApplicationData.xml
// OPTIONS: -Channel Experimental -Language C++ -Namespace Microsoft.Windows.Storage.ApplicationData -Path dev\Common\TerminalVelocityFeatures-ApplicationData.xml -Output dev\Common\TerminalVelocityFeatures-ApplicationData.h

#if defined(__midlrt)
namespace features
{
    feature_name Feature_ApplicationData = { DisabledByDefault, FALSE };
}
#endif // defined(__midlrt)

// Feature constants
#define WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_STORAGE_APPLICATIONDATA_FEATURE_APPLICATIONDATA_ENABLED 1

#if defined(__cplusplus)

namespace Microsoft::Windows::Storage::ApplicationData
{

__pragma(detect_mismatch("ODR_violation_WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_STORAGE_APPLICATIONDATA_FEATURE_APPLICATIONDATA_ENABLED_mismatch", "AlwaysEnabled"))
struct Feature_ApplicationData
{
    static constexpr bool IsEnabled() { return WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_STORAGE_APPLICATIONDATA_FEATURE_APPLICATIONDATA_ENABLED == 1; }
};

} // namespace Microsoft.Windows.Storage.ApplicationData

#endif // defined(__cplusplus)
