// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

// THIS FILE IS AUTOMATICALLY GENERATED; DO NOT EDIT IT

// INPUT FILE: C:\code\WinAppSdk\dev\Common\TerminalVelocityFeatures-AppNotifications.xml
// OPTIONS: -Channel Experimental -Language C++ -Namespace Microsoft.Windows.CallingPreviewSupport -Path C:\code\WinAppSdk\dev\Common\TerminalVelocityFeatures-AppNotifications.xml -Output C:\code\WinAppSdk\dev\Common\TerminalVelocityFeatures-CallingPreviewSupport.h

#if defined(__midlrt)
namespace features
{
    feature_name Feature_AppNotifications = { DisabledByDefault, FALSE };
    feature_name Feature_CallingPreviewSupport = { DisabledByDefault, FALSE };
}
#endif // defined(__midlrt)

// Feature constants
#define WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_CALLINGPREVIEWSUPPORT_FEATURE_APPNOTIFICATIONS_ENABLED 1
#define WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_CALLINGPREVIEWSUPPORT_FEATURE_CALLINGPREVIEWSUPPORT_ENABLED 1

#if defined(__cplusplus)

namespace Microsoft::Windows::CallingPreviewSupport
{

__pragma(detect_mismatch("ODR_violation_WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_CALLINGPREVIEWSUPPORT_FEATURE_APPNOTIFICATIONS_ENABLED_mismatch", "AlwaysEnabled"))
struct Feature_AppNotifications
{
    static constexpr bool IsEnabled() { return WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_CALLINGPREVIEWSUPPORT_FEATURE_APPNOTIFICATIONS_ENABLED == 1; }
};

__pragma(detect_mismatch("ODR_violation_WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_CALLINGPREVIEWSUPPORT_FEATURE_CALLINGPREVIEWSUPPORT_ENABLED_mismatch", "AlwaysEnabled"))
struct Feature_CallingPreviewSupport
{
    static constexpr bool IsEnabled() { return WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_CALLINGPREVIEWSUPPORT_FEATURE_CALLINGPREVIEWSUPPORT_ENABLED == 1; }
};

} // namespace Microsoft.Windows.CallingPreviewSupport

#endif // defined(__cplusplus)
