// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

// THIS FILE IS AUTOMATICALLY GENERATED; DO NOT EDIT IT

// INPUT FILE: dev\common\TerminalVelocityFeatures-Decimal.xml
// OPTIONS: -Channel Experimental -Language C++ -Namespace Microsoft.Windows.Foundation -Path dev\common\TerminalVelocityFeatures-Decimal.xml -Output dev\common\TerminalVelocityFeatures-Decimal.h

#if defined(__midlrt)
namespace features
{
    feature_name Feature_Decimal = { DisabledByDefault, FALSE };
}
#endif // defined(__midlrt)

// Feature constants
#define WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_FOUNDATION_FEATURE_DECIMAL_ENABLED 1

#if defined(__cplusplus)

namespace Microsoft::Windows::Foundation
{

__pragma(detect_mismatch("ODR_violation_WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_FOUNDATION_FEATURE_DECIMAL_ENABLED_mismatch", "AlwaysEnabled"))
struct Feature_Decimal
{
    static constexpr bool IsEnabled() { return WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_FOUNDATION_FEATURE_DECIMAL_ENABLED == 1; }
};

} // namespace Microsoft.Windows.Foundation

#endif // defined(__cplusplus)
