// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

// THIS FILE IS AUTOMATICALLY GENERATED; DO NOT EDIT IT

// INPUT FILE: dev\common\TerminalVelocityFeatures-DeploymentAPI.xml
// OPTIONS: -Channel Experimental -Language C++ -Namespace Microsoft.Windows.ApplicationModel.WindowsAppRuntime -Path dev\common\TerminalVelocityFeatures-DeploymentAPI.xml -Output dev\common\TerminalVelocityFeatures-DeploymentAPI.h

#if defined(__midlrt)
namespace features
{
    feature_name Feature_DeploymentAPI = { DisabledByDefault, FALSE };
    feature_name Feature_DeploymentRepair = { DisabledByDefault, FALSE };
}
#endif // defined(__midlrt)

// Feature constants
#define WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_APPLICATIONMODEL_WINDOWSAPPRUNTIME_FEATURE_DEPLOYMENTAPI_ENABLED 1
#define WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_APPLICATIONMODEL_WINDOWSAPPRUNTIME_FEATURE_DEPLOYMENTREPAIR_ENABLED 1

#if defined(__cplusplus)

namespace Microsoft::Windows::ApplicationModel::WindowsAppRuntime
{

__pragma(detect_mismatch("ODR_violation_WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_APPLICATIONMODEL_WINDOWSAPPRUNTIME_FEATURE_DEPLOYMENTAPI_ENABLED_mismatch", "AlwaysEnabled"))
struct Feature_DeploymentAPI
{
    static constexpr bool IsEnabled() { return WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_APPLICATIONMODEL_WINDOWSAPPRUNTIME_FEATURE_DEPLOYMENTAPI_ENABLED == 1; }
};

__pragma(detect_mismatch("ODR_violation_WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_APPLICATIONMODEL_WINDOWSAPPRUNTIME_FEATURE_DEPLOYMENTREPAIR_ENABLED_mismatch", "AlwaysEnabled"))
struct Feature_DeploymentRepair
{
    static constexpr bool IsEnabled() { return WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_APPLICATIONMODEL_WINDOWSAPPRUNTIME_FEATURE_DEPLOYMENTREPAIR_ENABLED == 1; }
};

} // namespace Microsoft.Windows.ApplicationModel.WindowsAppRuntime

#endif // defined(__cplusplus)
