// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

// THIS FILE IS AUTOMATICALLY GENERATED; DO NOT EDIT IT

// INPUT FILE: dev\common\TerminalVelocityFeatures-BadgeNotifications.xml
// OPTIONS: -Channel Experimental -Language C++ -Namespace Microsoft.Windows.BadgeNotifications -Path dev\common\TerminalVelocityFeatures-BadgeNotifications.xml -Output dev\common\TerminalVelocityFeatures-BadgeNotifications.h

#if defined(__midlrt)
namespace features
{
    feature_name Feature_BadgeNotifications = { DisabledByDefault, FALSE };
}
#endif // defined(__midlrt)

// Feature constants
#define WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_BADGENOTIFICATIONS_FEATURE_BADGENOTIFICATIONS_ENABLED 1

#if defined(__cplusplus)

namespace Microsoft::Windows::BadgeNotifications
{

    __pragma(detect_mismatch("ODR_violation_WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_BADGENOTIFICATIONS_FEATURE_BADGENOTIFICATIONS_ENABLED_mismatch", "AlwaysEnabled"))
        struct Feature_BadgeNotifications
    {
        static constexpr bool IsEnabled() { return WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_BADGENOTIFICATIONS_FEATURE_BADGENOTIFICATIONS_ENABLED == 1; }
    };

} // namespace Microsoft.Windows.BadgeNotifications

#endif // defined(__cplusplus)
