// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

// THIS FILE IS AUTOMATICALLY GENERATED; DO NOT EDIT IT

// INPUT FILE: dev\common\TerminalVelocityFeatures-BackgroundTask.xml
// OPTIONS: -Channel Experimental -Language C++ -Namespace Microsoft.Windows.ApplicationModel.Background -Path dev\common\TerminalVelocityFeatures-BackgroundTask.xml -Output dev\common\TerminalVelocityFeatures-BackgroundTask.h

#if defined(__midlrt)
namespace features
{
    feature_name Feature_BackgroundTask = { DisabledByDefault, FALSE };
}
#endif // defined(__midlrt)

// Feature constants
#define WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_APPLICATIONMODEL_BACKGROUND_FEATURE_BACKGROUNDTASK_ENABLED 1

#if defined(__cplusplus)

namespace Microsoft::Windows::ApplicationModel::Background
{

__pragma(detect_mismatch("ODR_violation_WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_APPLICATIONMODEL_BACKGROUND_FEATURE_BACKGROUNDTASK_ENABLED_mismatch", "AlwaysEnabled"))
struct Feature_BackgroundTask
{
    static constexpr bool IsEnabled() { return WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_APPLICATIONMODEL_BACKGROUND_FEATURE_BACKGROUNDTASK_ENABLED == 1; }
};

} // namespace Microsoft.Windows.ApplicationModel.Background

#endif // defined(__cplusplus)
