// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

// THIS FILE IS AUTOMATICALLY GENERATED; DO NOT EDIT IT

// INPUT FILE: dev\Common\TerminalVelocityFeatures-DynamicDependency.xml
// OPTIONS: -Channel Experimental -Namespace Microsoft.Windows.ApplicationModel.DynamicDependency

// Feature constants
#define WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_APPLICATIONMODEL_DYNAMICDEPENDENCY_FEATURE_GENERATIONID_ENABLED 1

#if defined(__cplusplus)

namespace Microsoft::Windows::ApplicationModel::DynamicDependency
{

__pragma(detect_mismatch("ODR_violation_WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_APPLICATIONMODEL_DYNAMICDEPENDENCY_FEATURE_GENERATIONID_ENABLED_mismatch", "AlwaysEnabled"))
struct Feature_GenerationId
{
    static constexpr bool IsEnabled() { return WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_APPLICATIONMODEL_DYNAMICDEPENDENCY_FEATURE_GENERATIONID_ENABLED == 1; }
};

} // namespace Microsoft.Windows.ApplicationModel.DynamicDependency

#endif // defined(__cplusplus)
