// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

// THIS FILE IS AUTOMATICALLY GENERATED; DO NOT EDIT IT

// INPUT FILE: TerminalVelocityFeatures-DynamicDependency.xml
// OPTIONS: Channel=Experimental

// Feature constants
#define WINDOWSAPPSDK_FEATURE_GETGENERATIONID_ENABLED 1

#if defined(__cplusplus)

namespace Microsoft::Windows::ApplicationModel::DynamicDependency
{

__pragma(detect_mismatch("ODR_violation_WINDOWSAPPSDK_FEATURE_GETGENERATIONID_ENABLED_mismatch", "AlwaysEnabled"))
struct Feature_GetGenerationId
{
    static constexpr bool IsEnabled() { return WINDOWSAPPSDK_FEATURE_GETGENERATIONID_ENABLED == 1; }
};

} // namespace Microsoft.Windows.ApplicationModel.DynamicDependency

#endif // defined(__cplusplus)
