// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

// THIS FILE IS AUTOMATICALLY GENERATED; DO NOT EDIT IT

// INPUT FILE: dev\Common\TerminalVelocityFeatures-DynamicDependency.xml
// OPTIONS: -Channel Experimental -Language C++ -Namespace Microsoft.Windows.ApplicationModel.DynamicDependency -Path dev\Common\TerminalVelocityFeatures-DynamicDependency.xml -Output dev\Common\TerminalVelocityFeatures-DynamicDependency.h

#if defined(__midlrt)
namespace features
{
    feature_name Feature_GenerationId = { DisabledByDefault, FALSE };
}
#endif // defined(__midlrt)

// Feature constants
#define WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_APPLICATIONMODEL_DYNAMICDEPENDENCY_FEATURE_GENERATIONID_ENABLED 1

#if defined(__cplusplus)

namespace Microsoft::Windows::ApplicationModel::DynamicDependency
{

__pragma(detect_mismatch("ODR_violation_WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_APPLICATIONMODEL_DYNAMICDEPENDENCY_FEATURE_GENERATIONID_ENABLED_mismatch", "AlwaysEnabled"))
struct Feature_GenerationId
{
    static constexpr bool IsEnabled() { return WINDOWSAPPRUNTIME_MICROSOFT_WINDOWS_APPLICATIONMODEL_DYNAMICDEPENDENCY_FEATURE_GENERATIONID_ENABLED == 1; }
};

} // namespace Microsoft.Windows.ApplicationModel.DynamicDependency

#endif // defined(__cplusplus)
