// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

// THIS FILE IS AUTOMATICALLY GENERATED; DO NOT EDIT IT

// INPUT FILE: .\dev\Common\TerminalVelocityFeatures-StoragePickers.xml
// OPTIONS: -Channel Experimental -Language C++ -Path .\dev\Common\TerminalVelocityFeatures-StoragePickers.xml

#if defined(__midlrt)
namespace features
{
    feature_name Feature_StoragePickers = { DisabledByDefault, FALSE };
}
#endif // defined(__midlrt)

// Feature constants
#define WINDOWSAPPRUNTIME_FEATURE_STORAGEPICKERS_ENABLED 1

#if defined(__cplusplus)

__pragma(detect_mismatch("ODR_violation_WINDOWSAPPRUNTIME_FEATURE_STORAGEPICKERS_ENABLED_mismatch", "AlwaysEnabled"))
struct Feature_StoragePickers
{
    static constexpr bool IsEnabled() { return WINDOWSAPPRUNTIME_FEATURE_STORAGEPICKERS_ENABLED == 1; }
};

#endif // defined(__cplusplus)