// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

// <auto-generated>
// Exclude this file from StyleCop analysis. This file isn't generated but is added to projects.
// DO NOT MODIFY. Changes to this file may cause incorrect behavior and will be lost on updates.
// </auto-generated>

using System;

namespace Microsoft.Windows.ApplicationModel.WindowsAppRuntime.BaseDirectoryCS
{
    class AutoInitialize
    {
        // Called by WindowsAppRuntimeAutoInitializer.cs
        internal static void AccessWindowsAppSDK()
        {
            // The Windows App SDK app manifest redirects framework DLL loads (and, for PublishSingleFile
            // apps, resource lookups) through %MICROSOFT_WINDOWSAPPRUNTIME_BASE_DIRECTORY%. Publish that
            // base directory here so the manifest SxS redirection and MRTCore can resolve it. This runs
            // for self-contained apps, matching the manifest generated by the Windows App SDK
            // SelfContained targets.
            Environment.SetEnvironmentVariable("MICROSOFT_WINDOWSAPPRUNTIME_BASE_DIRECTORY", AppContext.BaseDirectory);

            // Stamp the owning process id alongside the base directory. This is a process environment
            // variable, so it is inherited by child processes spawned via CreateProcess. Consumers
            // (MRTCore, undocked reg-free WinRT) honor the base directory only when this stamp matches
            // the current process, preventing a child from loading the parent's resources.pri (or from
            // being steered to read files from a parent-controlled directory).
            // See https://github.com/microsoft/WindowsAppSDK/issues/5987.
            Environment.SetEnvironmentVariable("MICROSOFT_WINDOWSAPPRUNTIME_BASE_DIRECTORY_PID",
                Environment.ProcessId.ToString(System.Globalization.CultureInfo.InvariantCulture));
        }
    }
}
