// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace Microsoft.PurojekutoTenpuret
{
    [contractversion(1)]
    apicontract PurojekutoTenpuretContract{};

    [contract(PurojekutoTenpuretContract, 1)]
    runtimeclass AppGraphManager
    {
        /// Get an AppGraph manager for the caller's context.
        static AppGraphManager Open();

        /// Return the user.
        String User { get; };
    };
}
