// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

#include <TerminalVelocityFeatures-StoragePickers.h>
namespace Microsoft.Windows.Storage.Pickers
{
    [feature(Feature_StoragePickers)]
    enum PickerViewMode
    {
        List,
        Thumbnail,
    };

    [feature(Feature_StoragePickers)]
    enum PickerLocationId
    {
        DocumentsLibrary,
        ComputerFolder,
        Desktop,
        Downloads,
        HomeGroup,
        MusicLibrary,
        PicturesLibrary,
        VideosLibrary,
        Objects3D,
        Unspecified,
    };

    [feature(Feature_StoragePickers)]
    runtimeclass PickFileResult 
    {
        String Path { get; };
    }

    [feature(Feature_StoragePickers)]
    runtimeclass FileOpenPicker
    {
        FileOpenPicker(Microsoft.UI.WindowId windowId);

        Microsoft.Windows.Storage.Pickers.PickerViewMode ViewMode;
        String SettingsIdentifier;
        Microsoft.Windows.Storage.Pickers.PickerLocationId SuggestedStartLocation;
        String CommitButtonText;
        Windows.Foundation.Collections.IVector<String> FileTypeFilter{ get; };

        [remote_sync] Windows.Foundation.IAsyncOperation<PickFileResult> PickSingleFileAsync();
        [remote_sync] Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVectorView<PickFileResult> > PickMultipleFilesAsync();
    }

    [feature(Feature_StoragePickers)]
    runtimeclass FileSavePicker
    {
        FileSavePicker(Microsoft.UI.WindowId windowId);

        String SettingsIdentifier;
        Microsoft.Windows.Storage.Pickers.PickerLocationId SuggestedStartLocation;
        String CommitButtonText;
        Windows.Foundation.Collections.IMap<String, Windows.Foundation.Collections.IVector<String> > FileTypeChoices{ get; };
        String DefaultFileExtension;
        Windows.Storage.StorageFile SuggestedSaveFile;
        String SuggestedFileName;

        [remote_sync] Windows.Foundation.IAsyncOperation<PickFileResult> PickSaveFileAsync();
    }

    [feature(Feature_StoragePickers)]
    runtimeclass PickFolderResult
    {
        String Path { get; };
    }

    [feature(Feature_StoragePickers)]
    runtimeclass FolderPicker
    {
        FolderPicker(Microsoft.UI.WindowId windowId);

        Microsoft.Windows.Storage.Pickers.PickerViewMode ViewMode;
        String SettingsIdentifier;
        Microsoft.Windows.Storage.Pickers.PickerLocationId SuggestedStartLocation;
        String CommitButtonText;
        Windows.Foundation.Collections.IVector<String> FileTypeFilter{ get; };

        [remote_sync] Windows.Foundation.IAsyncOperation<PickFolderResult> PickSingleFolderAsync();
    }
}
