// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
namespace Microsoft.Windows.Media.Capture
{
    [version(1.0)]
    typedef enum CameraCaptureUIMode
    {
        PhotoOrVideo = 0,
        Photo,
        Video,
    } CameraCaptureUIMode;

    [version(1.0)]
    typedef enum CameraCaptureUIPhotoFormat
    {
        Jpeg = 0,
        Png,
        JpegXR,
    } CameraCaptureUIPhotoFormat;

    [version(1.0)]
    typedef enum CameraCaptureUIVideoFormat
    {
        Mp4 = 0,
        Wmv,
    } CameraCaptureUIVideoFormat;

    [version(1.0)]
    typedef enum CameraCaptureUIMaxVideoResolution
    {
        HighestAvailable = 0,
        LowDefinition,
        StandardDefinition,
        HighDefinition,
    } CameraCaptureUIMaxVideoResolution;

    [version(1.0)]
    typedef enum CameraCaptureUIMaxPhotoResolution
    {
        HighestAvailable = 0,
        VerySmallQvga,
        SmallVga,
        MediumXga,
        Large3M,
        VeryLarge5M,
    } CameraCaptureUIMaxPhotoResolution;

    [default_interface]
    runtimeclass CameraCaptureUIPhotoSettings
    {
        CameraCaptureUIPhotoSettings();

        Boolean AllowCropping;
        Windows.Foundation.Size CroppedAspectRatio;
        Windows.Foundation.Size CroppedSizeInPixels;
        Microsoft.Windows.Media.Capture.CameraCaptureUIPhotoFormat Format;
        Microsoft.Windows.Media.Capture.CameraCaptureUIMaxPhotoResolution MaxResolution;
    }

    [default_interface]
    runtimeclass CameraCaptureUIVideoSettings
    {
        CameraCaptureUIVideoSettings();

        Boolean AllowTrimming;
        Microsoft.Windows.Media.Capture.CameraCaptureUIVideoFormat Format;
        Single MaxDurationInSeconds;
        Microsoft.Windows.Media.Capture.CameraCaptureUIMaxVideoResolution MaxResolution;
    }

    [default_interface]
    runtimeclass CameraCaptureUI
    {
        CameraCaptureUI(Windows.UI.WindowId window);
        //CameraCaptureUI(Microsoft.UI.WindowId window);

        CameraCaptureUIPhotoSettings PhotoSettings{ get; };
        CameraCaptureUIVideoSettings VideoSettings{ get; };

        Windows.Foundation.IAsyncOperation<Windows.Storage.StorageFile> CaptureFileAsync(Microsoft.Windows.Media.Capture.CameraCaptureUIMode mode);
    }
}
