// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.



namespace Microsoft.Windows.ApplicationModel.Background.UniversalBGTask
{
    [default_interface]
    runtimeclass Task : Windows.ApplicationModel.Background.IBackgroundTask
    {
        Task();
        void Run(Windows.ApplicationModel.Background.IBackgroundTaskInstance taskInstance);
    }
}
