name: Build CI Main

# Controls when the action will run. Triggers the workflow on pull requests
# for the target branch
on:
  pull_request:
    branches: [ main ]
    paths-ignore: 
      - '.github/ISSUE_TEMPLATE/**'
      - 'docs/**'
      - 'specs/**'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: checkout project
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      
    - name: setup msbuild
      uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0
      
    - name: setup nuget
      uses: NuGet/setup-nuget@fd55a6f3b34392fa83fde1454582407d8c714123 # v4.0

    - name: restore project packages
      run: nuget restore WindowsAppRuntime.sln

    - name: build x86
      run: msbuild /m /p:Configuration=Release,Platform=x86 WindowsAppRuntime.sln

    - name: build x64
      run: msbuild /m /p:Configuration=Release,Platform=x64 WindowsAppRuntime.sln

    - name: build ARM64
      run: msbuild /m /p:Configuration=Release,Platform=ARM64 WindowsAppRuntime.sln
